### ISSUE TITLE
Automatically and incorrectly writing to file

### ISSUE THREAD

**Issue by GideonWolfe** [neoclide/coc.nvim#1487] opened 2020-01-23 19:26 UTC
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-327-g97dcc48c9
node version: v13.6.0
coc.nvim version: 0.0.74-5445f64a56
term: rxvt-unicode-256color
platform: linux

## Messages

## Output channel: snippets


## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /home/gideon/.config/nvim/configs
fatal: not a git repository (or any of the parent directories): .git

## Output channel: prettier


## Output channel: highlight

[Info  - 11:19:03 AM] Highlight server running in node v13.6.0


```

## Describe the bug

When I write my file coc.nvim places incorrect symbols in the file.

If I have LaTeX code in between `$$ ... $$` in a markdown document, it renders as latex with markdown preview. 

However when I save the file, coc.nvim appends `$$`, making the file look like `$$ ... $$ $$`, which ruins the render.

Also if I have it arranged like so 

```
$$

...

$$
```

it will automatically delete the blank lines, turning it into 

```
$$
...
$$
```

## Reproduce the bug

Please look at the issue I opened [here](https://github.com/iamcco/markdown-preview.nvim/issues/125) when I thought the behavior was the fault of markdown-preview.

I have a standard coc.nvim configuration. 

I know it is coc because the command  `:au BufWritePre` returns 

```
--- Autocommands ---
coc_nvim  BufWritePre
    *         call s:SyncAutocmd('BufWritePre', +expand('<abuf>'))

```

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by oblitum** [comment] 2020-01-25 01:36
I write Latex with coc-texlab and vimtex and never hit this issue. You also simply ignored providing a testcase of your problem. No one can reproduce it if you don't post the minimal code that causes it.

**Comment by GideonWolfe** [comment] 2020-01-25 19:30
Ok, I said that I have a standard config. This is all of the code required to replicate the issue on my end.

```
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```

Here is the markdown I was working with.

```
$$
\nabla \times \vec{\mathbf{B}} -\, \frac1c\, \frac{\partial\vec{\mathbf{E}}}{\partial t} &
= \frac{4\pi}{c}\vec{\mathbf{j}}    \nabla \cdot \vec{\mathbf{E}} & = 4 \pi \rho \\

\nabla \times \vec{\mathbf{E}}\, +\, \frac1c\, \frac{\partial\vec{\mathbf{B}}}{\partial t} & = \vec{\mathbf{0}} \\

\nabla \cdot \vec{\mathbf{B}} & = 0

\end{array}$$
$$
```

You can see the first `$$` is directly after array (as per the [example](https://github.com/iamcco/markdown-preview.nvim) I am referencing), but when I write the file the second `$$` is added and the perfectly rendered latex is broken.

**Comment by oblitum** [comment] 2020-01-26 03:14
I can't reproduce the issue. I've put your latex snippet (without the ending `$$` duplicate) in a latex file, opened it with neovim, which loaded coc.nvim+coc-texlab for it, no issues writing it, it's unchanged.

**Comment by oblitum** [comment] 2020-01-26 03:20
A never mind, you're putting in on Markdown... let me check. Before that, just a note on:

> and the perfectly rendered latex is broken

Not sure how it's perfect given there's a `\end{array}` without a `\begin{array}`.

**Comment by oblitum** [comment] 2020-01-26 03:21
Unable to reproduce in Markdown either.

**Comment by oblitum** [comment] 2020-01-26 03:34
Due to luck, not proper test case, I was able to reproduce this behavior by formatting (`<Plug>(coc-format)`) the markdown with coc-prettier installed. I suspect you should have it installed, and you're configuring coc.nvim to automatically format files on save, which isn't enabled by default.

Please uninstall coc-prettier and check if the issue is gone, if so close this issue and open a new one on coc-prettier repository, with proper minimum test case.

**Comment by oblitum** [comment] 2020-01-26 03:44
Scratch that. It's not even a coc-prettier issue, [it's a _prettier_ issue](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASVAdKGsEMBGANrgAQ4wCWAtnAM5kYBucYwOVuMAFvgGbAAhAL5CSAWhwAaBrwBOuMAEYwUmfNY4ADrlmVchHMw0YO3PsACiIoWwzbdFfSRiiAZFgC8ahcAAsWihswIUMWW1MefgArERI4higCYgYwABMIGAYjcM5Iy1jXEi9fBk0KBlkuCAYcLDq8IlJyajossPZc8ysQjGkAalUcOQVlQYxh43s9AyZ2k07+YRFbKcdCZzcituMI8wAGWNqcbGwG5Jw0jO2cs0WCrb2604RU4B15AE8hdBBJEAhNJRoLRkKB3hAAO4ABR0CBBKFwjAgFFSvxA+HUAGs4DAAMraMAUKAAc2QMFkAFc4H8uDAqIQAOpcCjwWgEuC4uEsiiMFkfZDgWggv5E2hwXRQ+TEjjIXj6MV-KK0AAeAixONxuBoABkiXBZfLqSAlcrcUTiYQ4ABFCkZfVIOWEBUgexi2QCjiyTHpCFQNGaWREmAMlHcZAADj2fwDEDFDPkmgFAbo4uYaIAjrb4JKAfCQLhaGIoHA4KlS2jZHBMxRK5LcNLcAanUaxVQKGTKS3zZabXam86YAQQ6kw0gAEx-cm4CiEc0AYQgVBlKCg0H1fwpYoAKgR4Y7nYwqQBJKBl2C4sCBwEAQVPuJgH0t-bgIiAA).

Report it on prettier repository: https://github.com/prettier/prettier.

**Closed** 2020-01-27 15:22 UTC
