### ISSUE TITLE
RPC took too much time when editing bash script in VIM

### ISSUE THREAD

**Issue by hexchain** [neoclide/coc.nvim#398] opened 2019-02-01 11:23 UTC
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.
```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jan 15 2019 00:11:27)
node version: v8.9.0
coc.nvim version: 0.0.50
term: dumb
platform: linux

## Error messages
```

**Describe the bug**
When trying to enter something into a bash script in vim, the editor gets freezed for a while.

**To Reproduce**

1. Open a bash file/script
2. Press `i` and try to enter something

**Other logs**
`profile.log`: 

```
FUNCTION  nvim#rpc#request()
    Defined: ~/.config/yarn/global/node_modules/vim-node-rpc/autoload/nvim/rpc.vim line 103
Called 7 times
Total time:   5.075094
 Self time:   5.007997
count  total (s)   self (s)
    7   0.000073   0.000036   if !nvim#rpc#check_client(a:clientId)
                                return
    7              0.000000   endif
    7              0.000020   let args = get(a:, 1, [])
    7   5.074905   5.007845   let res = ch_evalexpr(s:channel, [a:clientId, a:method, args], {'timeout': 5000})
    7              0.000048   if type(res) == 1 && res ==# '' | return '' | endif
    6              0.000011   let [l:errmsg, res] =  res
    6              0.000005   if l:errmsg
                                echohl Error | echon '[rpc.vim] client error: '.l:errmsg | echohl None
    6              0.000003   else
    6              0.000003     return res
                              endif
```

I don't have any bash language server, and also did not encounter this issue in nvim.

**Comment by chemzqm** [comment] 2019-02-01 18:13
It's a common issue, already fixed on master.

**Closed by chemzqm** 2019-02-01 18:13 UTC

**Comment by hexchain** [comment] 2019-02-02 15:58
I can still reproduce this in v0.0.51. Am I missing something?

**Comment by chemzqm** [comment] 2019-02-02 21:20
I can't reproduce your problem, checkout https://github.com/neoclide/coc.nvim/wiki/F.A.Q#my-vim-is-blocked-sometimes

**Comment by hexchain** [comment] 2019-02-07 15:08
I have successfully reproduced the problem with a minimal vimrc:

```vim
set nocompatible
syntax on
filetype plugin indent on

call plug#begin('~/.vim/bundle')

Plug 'neoclide/coc.nvim', {'tag': '*', 'do': { -> coc#util#install()}}
Plug 'w0rp/ale'
Plug 'vim-airline/vim-airline'

call plug#end()

set hidden

" vim-airline
let g:airline_skip_empty_sections = 1
" Note that the following line is set by default:
" let g:airline#extensions#ale#enabled = 1
```

For now I can just turn off `g:airline_skip_empty_sections` or `g:airline#extensions#ale#enabled`, but I would really like to know (and possibly solve) the root cause of this, if possible.

**Comment by chemzqm** [comment] 2019-02-08 05:11
@hexchain it's problem of ale, checkout https://github.com/w0rp/ale/issues/2132
