### ISSUE TITLE
floating window is empty

### ISSUE THREAD

**Issue by Laumm** [neoclide/coc.nvim#1963] opened 2020-05-20 14:04 UTC
### QUESTION
When i move the cursor to the wrong position， floating a window with nothing 
### ENVIRONMENT

- macOS Mojave 10.14.6
-vim 8.1.1722

### coc-config
{
    "suggest.autoTrigger": "none",
    "suggest.noselect": false,
    "list.source.grep.args": ["--color=ansi"],
    "languageserver": {
        "golang": {
            "command": "gopls",
              "rootPatterns": ["go.mod"],
              "filetypes": ["go"]
        }
    },
    "coc.preferences.extensionUpdateCheck": "daily",
    "list.insertMappings": {
        "<C-v>": "eval:@+",
        "<C-r>": "eval:@@"
    }
}
#### diagnostics
![image](https://user-images.githubusercontent.com/42160960/82455194-42600a00-9ae5-11ea-90b3-ae0e75e19ce7.png)
 #### floating window show
![image](https://user-images.githubusercontent.com/42160960/82455259-54da4380-9ae5-11ea-8cf0-30dbe5f93483.png)

**Comment by chemzqm** [comment] 2020-05-20 16:14
Duplicate of #1949

**Closed by chemzqm** 2020-05-20 16:14 UTC
