### ISSUE TITLE
It appears like the buffer is going out of sync with the language server

### ISSUE THREAD

**Issue by francium** [neoclide/coc.nvim#1552] opened 2020-02-09 15:35 UTC
Here's some screenshots of what I mean.

![coc-1](https://user-images.githubusercontent.com/15352422/74104829-b4a87200-4b26-11ea-862d-bdbd62ac287f.png)
![coc-2](https://user-images.githubusercontent.com/15352422/74104831-b5410880-4b26-11ea-94c7-ee9e0ac625d2.png)
![coc-3](https://user-images.githubusercontent.com/15352422/74104833-b5410880-4b26-11ea-846a-469429c8102b.png)

It's a strange error state. It looks like the buffer's content are out of sync with what the language server is reading -- almost like the language server is a bit behind and hasn't received the most up to date source to check.

I fix this by restarting coc using a mapping that calls `CocRestart`.

It occurs regularly, but not consistently. I don't have a way to make it occur on command, it just sort of happens randomly.

I do work on a very large codebase, angular+typescript, but I don't see this issue occurring on multiple files, just a single file that I'm currently editing.

If I can be of more help please let me know.

**Comment by chemzqm** [comment] 2020-02-14 16:37
Duplicate of #1385

**Closed by chemzqm** 2020-02-14 16:37 UTC
