### ISSUE TITLE
Multiuser support: EACCES: permission denied, open '/tmp/node-client.log'

### ISSUE THREAD

**Issue by zhou13** [neoclide/coc.nvim#824] opened 2019-05-30 19:31 UTC
## Result from CocInfo

```
## versions

vim version: NVIM v0.3.7
node version: v11.15.0
coc.nvim version: 0.0.67
term: xterm-256color
platform: linux

## Error messages

## Output channel: highlight

[Info  - 12:25:24 PM] Highlight server running in node v11.15.0
```

## Describe the bug

I installed `coc.nvim` for both my user account and the root account. `coc.nvim` will produce an error in some cases.

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```
- `nvim -u mini.vim`
- quit nvim with `:quit`
- `sudo nvim -u mini.vim`

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/576382/58659007-bb63c180-82d6-11e9-8084-8110ef2f3a1a.png)

**Comment by oblitum** [comment] 2019-05-30 19:51
Possibly duplicate of #317

**Comment by chemzqm** [comment] 2019-05-30 21:06
It's fixed on master.

**Comment by zhou13** [comment] 2019-05-30 21:11
I just did a `PlugUpdate` and `CocInfo` returns `coc.nvim version: 0.0.68`. But it seems the bug is still there.

**Comment by chemzqm** [comment] 2019-05-30 21:19
remove '/tmp/node-client.log' and try again.

**Comment by zhou13** [comment] 2019-05-30 22:34
It is still there. After I open nvim, `/tmp/node-client.log` with permission `-rw-r--r--` is created. I guess that might be due to the usage of tmpfs in `/tmp` as suggested in #317.

**Comment by chemzqm** [comment] 2019-05-31 01:39
There will no log file for root user, and the file mode would be 0x666.

**Closed** 2019-05-31 01:38 UTC
