### ISSUE TITLE
Latest release commit (8909a94) broke coc_global_extensions

### ISSUE THREAD

**Issue by npearson72** [neoclide/coc.nvim#1881] opened 2020-05-09 22:38 UTC
They just don't work on a fresh install. No extensions get installed. Nothing in the package.json.

When I revert to `244b439` they work just fine.

Sorry for not filling out all the details as typical in a bug report, but this should be easily reproducible.

**Comment by azhang** [comment] 2020-05-09 22:59
wow good to see this as I've spent the last 2 hours trying to figure out why it wasn't working. First time coc user -_-

**Comment by nkcfan** [comment] 2020-05-09 23:44
```
8909a94 2020-05-09 | chore(plugin): use eslint replace tslint (origin/release) [Qiming Zhao]
```
This commit also broke ccls. I have spent the last 1 hour trying to figure out why a `node` upgrade broke everything, finally not a `node` issue.

**Comment by npearson72** [comment] 2020-05-10 00:11
I propose rolling it back, but am not familiar with your workflow.

**Comment by Alexey104** [comment] 2020-05-10 00:42
The same problem.
Language servers also stopped working.

**Comment by fsouza** [comment] 2020-05-10 02:16
Yeah after that change external processes are not launching anymore. Any laguageserver will simply not start.

I have a potential fix in #1882, but there's a chance other similar errors happened as part . I'd recommend reviewing all changes from `!== false` or `=== false` to simple truthy checks.

**Comment by oblitum** [comment] 2020-05-10 02:21
Duplicate of #1878.

**Comment by chemzqm** [comment] 2020-05-11 09:02
@fsouza I've did a review and fixed similar issues which caused by eslint autofix with `no-unnecessary-boolean-literal-compare` set to `error`

**Comment by fsouza** [comment] 2020-05-11 12:54
@chemzqm thank you very much!

**Comment by npearson72** [comment] 2020-05-11 16:24
@fsouza, @oblitum, and @chemzqm I just tested on release `commit 97b6e17533574c016a484030c8041b19a7cde400` and still not working.

Should I be using `master`?

**Comment by chemzqm** [comment] 2020-05-11 16:26
It's not fixed

**Comment by glepnir** [comment] 2020-05-12 09:45
got same error here.

**Closed** 2020-05-12 11:52 UTC

**Comment by npearson72** [comment] 2020-05-12 18:29
Thank you @chemzqm !
