### ISSUE TITLE
CocList suddenly closes

### ISSUE THREAD

**Issue by arbitrary-dev** [neoclide/coc.nvim#1020] opened 2019-07-24 15:21 UTC
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled May 30 2019 19:25:43)
node version: v12.4.0
coc.nvim version: 0.0.73-1ea838ee4e
term: Apple_Terminal
platform: darwin

## Messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"build.sbt" 809L, 24987C

## Describe the bug

`:CocList` window suddenly closes leaving a new line with `B` in the current buffer.

## Reproduce the bug

1. Open `vim`
2. Run `:CocList`
3. Scroll back and forth with UP & DOWN keys several times
4. Window suddenly closes & a new line with `A` (in case of UP) or `B` (DOWN) appears

I believe `A`'s & `B`'s that appear are related to how UP & DOWN keys are encoded in terminal, something like `^[[A` & `^[[B`.

- Repoducible with `mini.vim`：
  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

**Comment by chemzqm** [comment] 2019-07-25 18:51
Should be problem of your terminal, it send `<esc>` to vim, so the list get closed.

**Comment by arbitrary-dev** [comment] 2019-08-13 04:11
To improve reproducibility, the `<Up>` could be hold while scrolling the item list up.

**Comment by arbitrary-dev** [comment] 2019-08-13 04:15
Also, the problem manifests itself differently when scrolling up with `<C-k>` on hold, there are console error sounds (term: Apple_Terminal), but not when holding `<C-j>` while scrolling down.

**Comment by xinhangliu** [comment] 2019-09-07 12:00
Encounter the same problem.

termimals: terminal.app | alacritty | item2
macOS 10.14.6
vim 8.1.1722
nodejs v12.10.0
coc.nvim 0.0.57

![Untitled](https://user-images.githubusercontent.com/21138560/64474632-0df02c00-d1aa-11e9-85a5-fc6b5e12f1ff.gif)

**Comment by arbitrary-dev** [comment] 2019-09-09 14:08
Also reproducible in Linux, when holding the `DOWN` key...

## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 30 2019 20:40:47)
node version: v8.12.0
coc.nvim version: 0.0.74-c97d41aa1e
term: dumb (actually it's rxvt-unicode)
platform: linux

**Comment by arbitrary-dev** [comment] 2019-09-09 14:11
Probably some race condition due to asyncronously handling complex keys (the ones which consist of two elements `<esc>B`)

**Comment by arashm** [comment] 2019-10-03 10:56
I have the same issue on both Linux and Mac.

**Comment by oblitum** [comment] 2019-11-03 17:16
Happens for me on ArchLinux too, but just on Vim, only when holding `DOWN`/`UP`.

**Comment by igorsol** [comment] 2019-11-16 20:52
For me this also sometimes happens when:
- vim is in insert mode
- I press `Esc` and then quickly `Up` or `Down`
- After this new line is inserted with symbol `A` or `B`. Vim is still in insert mode and coc's autocompletion menu appears

This behavior seems to be bound to the vim's buffer somehow. For example at the moment of writing this I have several cpp files open in vim. For some of those files this happens every time I press Esc-Up or Esc-Down. For other files this does not happen at all. I tried to open buffer in other window or tab but this weird behavior moves with the buffer.

**Comment by chemzqm** [comment] 2019-11-17 07:03
> I press Esc 

The list will always be closed after `<exc>`, you have to use `<C-o>`

**Comment by chemzqm** [comment] 2019-11-17 08:30
Should be bug of vim, the window get closed by vim when coc.nvim send commands to vim frequently.

**Closed by chemzqm** 2019-11-17 08:30 UTC
Labels: wontfix

**Comment by gmolau** [comment] 2019-11-17 10:54
I understand that issues like this are difficult to address, but I want to point out that this currently breaks the list feature altogether for me. If this really can't be fixed that would to me seem to raise the question whether coc should really have its own list implementation at all, rather than focusing on providing a clean API for existing tools like fzf (see also the heavily upvoted #307 ).

**Comment by chemzqm** [comment] 2019-11-18 01:56
@gmolau there're apis provided, it's your choice to use list feature or not.

**Comment by igorsol** [comment] 2019-11-18 10:28
> The list will always be closed after `<exc>`, you have to use `<C-o>`

Sorry if I was not clear enough but what I've described in my comment was not in the list. That was in insert mode in ordinary source code buffer. I just tried to add more information hoping it might help with debugging the issue.

Nevertheless I can also reproduce the issue in the list as it is described above.

**Comment by markus-fe** [comment] 2021-07-07 16:10
Why has this issue been closed? The pop menu suddenly disappearing sadly is a deal-breaker to me.

Are there any workarounds? Does using neovim solve this issue?

```
vim version: VIM - Vi IMproved 8.2 8023046
version: v14.17.0
nvim version: 0.0.80-131f6b267f
nvim directory: /home/user/.vim/pack/coc/start/coc.nvim
term: dumb
platform: linux

GNOME Terminal 3.38.3
```

**Comment by chemzqm** [comment] 2021-07-08 04:56
> Why has this issue been closed? The pop menu suddenly disappearing sadly is a deal-breaker to me.
> 
> Are there any workarounds? Does using neovim solve this issue?
> 
> ```
> vim version: VIM - Vi IMproved 8.2 8023046
> node version: v14.17.0
> coc.nvim version: 0.0.80-131f6b267f
> term: dumb
> platform: linux
> 
> GNOME Terminal 3.38.3
> ```
> 
> Update: Doesn't work with xterm as well.
> Workaround: Use neovim (issue not present).
> 
> Not everyone has the luxury to switch between vim and neovim. Are vim developers aware, is there any linked issue on vim side?

Your have to provide information needed for us to reproduce, it's known issue that CocList would be closed by `<Up>` and `<Down>` https://github.com/neoclide/coc.nvim/wiki/F.A.Q#coclist-is-broken-when-holding-up-or-down-on-vim, we don't know how could that happened.

**Comment by markus-fe** [comment] 2021-07-08 07:35
@chemzqm Thank you  for mentioning the FAQ entry, which suggests `<C-j>` `<C-k>` on insert mode as workaround, I somehow missed it. This works!

I personally switched directly to neovim, as I like its better community integration.
