### ISSUE TITLE
gopls completion within snippet cancels the snippet session

### ISSUE THREAD

**Issue by jackielii** [neoclide/coc.nvim#1601] opened 2020-03-03 14:42 UTC
This issue is moved from https://github.com/neoclide/coc-snippets/issues/101

![coc-snippet-error](https://user-images.githubusercontent.com/360983/75776084-3157f600-5d4b-11ea-9c7f-e5f41649cfc0.gif)

Steps to reproduce:

1. minimal-coc.nvim
```
set nocompatible
set runtimepath^=/home/jackieli/.config/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
```
2. `CocConfig`
```
{
  "languageserver": {
    "golang": {
      "command": "gopls",
      "initializationOptions": {
        "usePlaceholders": false,
        "completeUnimported": true,
        "static_check": true,
        "hoverKind": "FullDocumentation"
      },
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"]
    }
  }
}
```
3. `nvim -u ~/.config/nvim/minimal-coc.vim main.go`
4. `:CocCommand snippets.editSnippets` and insert a simple snippet
```
snippet fori "for 0..N-1 { ... }"
for ${1:i} := 0; $1 < ${2:N}; $1++ {
	${0:${VISUAL}}
}
endsnippet
```
5. edit main.go like so:
```
package main

func main(){
   fori<C-n><C-y> // C-n to go to the snippet, C-y to accept the snippet
}
```
6. use `<C-j>` to jump to the second placeholder, and input flag.N, and then `<C-y>` to accept flag.Narg(), then press `<C-j>` to jump to the next placeholder, at this point, line break is inserted instead of jumping to the next placeholder

Further diagnostic shows that in [`snippets/session.ts:136`](https://github.com/neoclide/coc.nvim/blob/master/src/snippets/session.ts#L136). the `edit.range` returns the wrong range: edit.range.start.line should be 16, but it's 15. I suspect this has something to do with: https://github.com/neoclide/coc.nvim/issues/1001

If comment out the `this.deactivate` within `if (!placeholder)` check block, it works

**Comment by fannheyward** [comment] 2020-03-03 14:58
How do you jump to next placeholder? 

1. on `fori` I use `<C-y>`, got

```
    for i := 0; i < N; i++ {
        
    }
```

2. the cursor current on `i`, then I use `<C-j>` to `N`, input `flag.N`, `flag.NArg~` shows in completion items list, `enter` to complet, this will also do auto import `flag`, got:

```
    for i := 0; i < flag.NArg()|; i++ {
        
    }
```

cursor is behind `flag.NArg()`. `<C-j>` jumps to final placeholder, got:

```
    for i := 0; i < flag.NArg(); i++ {
        |
    }

```

**Comment by jackielii** [comment] 2020-03-03 15:01
@fannheyward Thanks for replying, Strange... I'm using <C-j> to jump to N etc, exactly the same steps as yours, Is there a smaller config I should use to reproduce the problem?

Regards,

**Comment by jackielii** [comment] 2020-03-03 15:03
@fannheyward I realised I need to quote the `<C-?>`, otherwise they all disappear. Edited

**Comment by fannheyward** [comment] 2020-03-03 15:04
what's the `<C-?>`?

**Comment by fannheyward** [comment] 2020-03-03 15:05
What's your `:verbose imap <C-j>`?

**Comment by jackielii** [comment] 2020-03-03 15:06
@fannheyward I meant `<C-j>` `<C-y>` etc, I have to use back tick to quote them. sorry for the confusion

I'm using minimal mapping, so `:verbose imap <C-j>` returns nothing

**Comment by fannheyward** [comment] 2020-03-03 15:09
Still can't reproduce...

**Comment by jackielii** [comment] 2020-03-03 15:19
added: `console.log(edit.range)` in snippets/session.ts:

![image](https://user-images.githubusercontent.com/360983/75789620-e1d0f480-5d61-11ea-99fe-04721833878e.png)


log attached:
[coc-nvim.log](https://github.com/neoclide/coc.nvim/files/4281993/coc-nvim.log)


fori triggered at line 180 in the log: 
```
2020-03-03T15:16:14.492 DEBUG (pid:4523) [events] - Event: MenuPopupChanged [
  {
    col: 10,
    row: 6,
    scrollbar: true,
    completed_item: {
      word: 'fori',
      menu: 'for 0..N-1 { ... } [S]',
      user_data: '{"cid":1583248574,"source":"snippets","index":0}',
      info: '',
      kind: 'S',
      abbr: 'fori~'
    },
    width: 118,
    height: 37,
    size: 47
  },
  5
]
```

and at the end of the log, the `flag.N` is accepted:
```
2020-03-03T15:16:18.818 DEBUG (pid:4523) [events] - Event: CompleteDone [
  {
    word: 'flag.NArg',
    menu: 'func() int [LS]',
    user_data: '{"cid":1583248577,"source":"languageserver.golang","index":0,"signature":"func() int"}',
    info: 'NArg is the number of arguments remaining after flags have been processed.\n',
    kind: 'f',
    abbr: 'flag.NArg~'
  }
]
2020-03-03T15:16:18.819 DEBUG (pid:4523) [events] - Event: CursorMovedI [ 1, [ 6, 27 ] ]
2020-03-03T15:16:18.820 DEBUG (pid:4523) [events] - Event: TextChangedI [ 1 ]
2020-03-03T15:16:18.877 INFO (pid:4523) [server] - { start: { line: 5, character: 17 }, end: { line: 5, character: 25 } }
```
you can see the value of the `edit.range` shows `{ start: { line: 5, character: 17 }, end: { line: 5, character: 25 } }`

**Comment by fannheyward** [comment] 2020-03-03 15:23
When input `flag.N`, `flag.NArg~` shows in completion lists, and after `<enter>`, I got `flag.NArg()`, but your gif shows you got `flag.NArg`. This is the different between you and me.

**Comment by jackielii** [comment] 2020-03-03 15:29
@fannheyward I think I know what's going on! (BTW, I got `flag.NArg~` too)

When I started with the `main.go` like this:

```
package main

func main() {
}
```
When completing flag.NArg, the language server inserted a import statment like so:
```
  package main

  import "flag" <---- inserted

  func main() {
>>        for i := 0; i < flag.NArg; i++ {

          }
  }
```
This is why the `edit.range` is wrong

**Comment by fannheyward** [comment] 2020-03-03 15:34
![5](https://user-images.githubusercontent.com/345274/75791301-58441580-5da7-11ea-9017-7d19fea9a0a8.gif)

mini.vim is same as yours. The auto import also work for me.

**Comment by fannheyward** [comment] 2020-03-03 15:37
Do you get `flag.NArg` or `flag.NArg()` after `<C-y>`?

**Comment by jackielii** [comment] 2020-03-03 15:40
@fannheyward I get `flag.NArg`

Wondering why I don't get `flag.NArg()`....

**Comment by oblitum** [comment] 2020-03-03 16:04
`<c-n>` browse items completing without snippet expansion, `<c-y>`  confirms an item and expands the snippet. Only through `<c-y>` you can get parentheses/argument-placeholders.

**Comment by fannheyward** [comment] 2020-03-03 16:06
@oblitum can you reproduce this issue?

**Comment by jackielii** [comment] 2020-03-03 16:09
@oblitum I'm using `<C-y>`to confirm the item

**Comment by oblitum** [comment] 2020-03-03 16:28
@jackielii I also was not getting `flag.NArg()`, it's happening because in your testcase the `"flag"` package is not yet imported, it expands with parentheses included when it's already imported only.

@fannheyward I do reproduce the issue.

**Comment by oblitum** [comment] 2020-03-03 16:30
It should possibly be related, or simply a duplicate of #1562, which broke nested snippets. This seems a special case of nested snippets.

**Comment by jackielii** [comment] 2020-03-03 23:09
reproduced the issue with docker. Dockerfile source at: https://github.com/jackielii/coc-debug-docker

![coc-snippet-error-docker-min](https://user-images.githubusercontent.com/360983/75828217-419bbf80-5da3-11ea-8d59-70b2246b37b0.gif)

steps: 
1. `docker run --rm -it tespkg/coc-debug-go bash`
2. `nvim -u /minimal-coc.nvim main.go`
3. `:CocInstall coc-snippets`
4. `:CocCommand snippets.editSnippets`
5. add snippets:
```
snippet fori "for 0..N-1 { ... }"
for ${1:i} := 0; $1 < ${2:N}; $1++ {
	${0:${VISUAL}}
}
endsnippet
```
6. resume edit main.go with source:
```
package main

func main(){
    fori<C-y>
}
```
7. `<C-j>` to jump to 2nd placeholder then type `flag.NArg<C-y>` then `<C-j>` to jump to next placeholder, here inserted line break instead

**Comment by fannheyward** [comment] 2020-03-04 02:35
Very strange: I use same nvim + mini.vim + `coc-snippets` only, on macOS, it's OK, but on Ubuntu can reproduce this issue.

`NVIM v0.5.0-404-g49cd750d6`, both download from GitHub nightly release.

mini.vim

```
set nocompatible
set runtimepath^=$HOME/.config/nvim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
```

steps:

`fori`, `<C-y>`, `<C-j>` to `N`, `flag.` to get `flag.NArg~`, `<C-y>` to confirm and expand to `flag.NArg()`, `<C-j>` jumps to final position.

Another different: when cursor on `N`, after input `flag.`, I got `flag.NArg~` as the first completion item on macOS, but `flag.Arg~` as the first completion item on Ubuntu. I suspect it's a LS error. More info are needed.

**Comment by oblitum** [comment] 2020-03-04 04:46
I think presence of parentheses and order of items may be other issues that are not related to the snippet cancellation issue, which happens for be whether or not parentheses is inserted, as it happens in both situations. I'm not sure #1562 is the general form of this, but it's a related behavior with with more minimal test, and the test for clangd there also applies for gopls.

**Comment by jackielii** [comment] 2020-03-04 18:07
@fannheyward @chemzqm did some more digging, it turns out at the TextChangedI on Ubuntu is carrying the wrong information. 
In https://github.com/neoclide/coc.nvim/blob/master/src/handler/index.ts#L191 it calls `coc#util#cursor()` to get line number etc, but this function looks like:

```
" get cursor position
function! coc#util#cursor()
  let pos = getcurpos()
  let content = pos[2] == 1 ? '' : getline('.')[0: pos[2] - 2]
  return [pos[1] - 1, strchars(content)]
endfunction
```
it returns pos[1] - 1 which is the line number minus 1...

Any reason why it minus 1??

**Comment by jackielii** [comment] 2020-03-04 23:57
@fannheyward @chemzqm sorry I was barking at the wrong tree. The problem seems to be at the updatePlaceHolder: when I type, the current placeholders range is updated, e.g. start: {line:9, char:15}, end: {line:9, char: 15} will be the value when I jump to this placeholder and edit it. But somehow, accepting a completion doesn't trigger this logic, this might also be the reason @fannheyward can't reproduce it on Mac... Still trying to find the right fix

**Comment by jackielii** [comment] 2020-03-05 00:53
@fannheyward did a very imperative fix, please can you check

**Comment by chemzqm** [comment] 2020-03-10 09:54
Should be fixed now.

**Closed by chemzqm** 2020-03-10 09:54 UTC
Labels: help wanted

**Comment by jackielii** [comment] 2020-03-10 09:57
Confirm this is fixed as well. Thanks @chemzqm !
