### ISSUE TITLE
Delayed tabline update when a tab is closed

### ISSUE THREAD

**Issue by wwwjfy** [neoclide/coc.nvim#1323] opened 2019-11-02 16:47 UTC
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.2
node version: v12.12.0
coc.nvim version: 0.0.74-a52dec0522
term: iTerm.app
platform: darwin

## Messages
```

## Describe the bug

When there are multiple tabs, closing one tab won't update tabline immediately.
For example, there are 3 files (a, b, c) open `nvim -p a b c`, the tabline is `[a] b c` ([a] means it's highlighted). When `a` is closed using `:q`, the tabline becomes `a [b] c`. Switching to `c` could trigger the update, making it `[b] c`, which should be the case after closing `a`.

## Reproduce the bug

- Create file `init.vim` with：
```vim
call plug#begin()
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
```
- Start neovim with command: `nvim -p a b c`
- Execute `:q` to close file `a`

## Investigation

I tried to locate the bug, and found that it's caused by BufUnload hook, and the last part inside coc is `diagnostic/buffer.ts`, `clear()` calls `nvim.resumeNotification(false, true)` in neovim package.
If I comment the line `node_modules/@chemzqm/neovim/lib/transport/base.js` line 50:
`this.notify('nvim_call_atomic', [list]);`, it'll work as expected.
(I could not find the code in this neovim fork)

**Comment by wwwjfy** [comment] 2019-11-02 18:08
I think I found the reason. In `@chemzqm/neovim/lib/transport/base.js`, line 50, also line 45 (version 5.1.9), `list` is already an array, so it should not be wrapped by `[]` again.
`this.notify('nvim_call_atomic', [list]);` => `this.notify('nvim_call_atomic', list);`

@chemzqm could you help to confirm? As you are the owner of this package and that repository is not updated so I can't send a pull request.

Before change: the method and args sent to `nvim_call_atomic` is:
`nvim_call_atomic` and
```
[
  [
    [ 'nvim_call_function', [Array] ],
    [ 'nvim_command', [Array] ],
    [ 'nvim_call_function', [Array] ]
  ]
]
```
You can see there is an extra wrapper.

**Comment by wwwjfy** [comment] 2019-11-02 18:11
Looks like this is the repository https://github.com/neoclide/neovim. The link in npmjs is outdated, pointing to https://github.com/chemzqm/node-client

I'll send a PR there.

**Comment by wwwjfy** [comment] 2019-11-03 14:56
Obviously I was wrong. Please help to check what's the problem here.

**Comment by wwwjfy** [comment] 2019-11-03 15:14
https://github.com/neoclide/coc.nvim/blob/master/src/diagnostic/buffer.ts#L162
This seems to be the command causing the issue for me.

**Comment by chemzqm** [comment] 2019-11-04 01:46
Can't reproduce, could be bug of your neovim.

**Comment by wwwjfy** [comment] 2019-11-04 04:58
@chemzqm May I know your environment? I've reproduced it in macOS 10.14 and 10.15, but not ubuntu 18.04

**Comment by chemzqm** [comment] 2019-11-04 05:02
MacOS 10.15

**Comment by wwwjfy** [comment] 2019-11-05 17:04
I tried on a cleanly installed macOS 10.14 and have the same problem. It might be something wrong in neovim. I'll try to dig deeper.

**Comment by yan12125** [comment] 2019-11-07 12:57
I got the same issue. Here is my environment:
```
## versions

vim version: NVIM v0.4.2
node version: v12.13.0
coc.nvim version: 0.0.74-377c2729b9
term: xterm-256color
platform: linux

## Messages
```
I'm using up-to-date Arch Linux. I will try to investigate more, too.

**Comment by yan12125** [comment] 2019-11-08 16:09
I found that coc.nvim runs `:redraws` upon `BufUnload`, which causes the issue. Here is a stack trace:
```
    at DiagnosticBuffer.setDiagnosticInfo (/home/yen/var/syncthing/dotfiles/toplevel/nvim/third_party/coc.nvim/build/index.js:51660:37)
    at DiagnosticBuffer.clear (/home/yen/var/syncthing/dotfiles/toplevel/nvim/third_party/coc.nvim/build/index.js:51745:14)
    at DiagnosticManager.disposeBuffer (/home/yen/var/syncthing/dotfiles/toplevel/nvim/third_party/coc.nvim/build/index.js:50496:13)
    at /home/yen/var/syncthing/dotfiles/toplevel/nvim/third_party/coc.nvim/build/index.js:50152:18
    at CallbackList.invoke (/home/yen/var/syncthing/dotfiles/toplevel/nvim/third_party/coc.nvim/build/index.js:16834:39)
    at Emitter.fire (/home/yen/var/syncthing/dotfiles/toplevel/nvim/third_party/coc.nvim/build/index.js:16892:36)
    at Workspace.onBufUnload (/home/yen/var/syncthing/dotfiles/toplevel/nvim/third_party/coc.nvim/build/index.js:23185:38)
    at /home/yen/var/syncthing/dotfiles/toplevel/nvim/third_party/coc.nvim/build/index.js:15193:47
    at Array.map (<anonymous>)
    at Events.fire (/home/yen/var/syncthing/dotfiles/toplevel/nvim/third_party/coc.nvim/build/index.js:15192:44)
```
The stack trace is generated from 465d0816bbaf13ec0ca63cf238179a84999b3ae9 with the follow debug codes:
```Diff
diff --git a/build/index.js b/build/index.js
index 1e0e2d0b..57434296 100644
--- a/build/index.js
+++ b/build/index.js
@@ -30182,6 +30182,7 @@ class StatusLine {
             this._text = text;
             nvim.pauseNotification();
             this.nvim.setVar('coc_status', text, true);
+            logger.debug("redraws", new Error().stack);
             this.nvim.command('redraws', true);
             this.nvim.call('coc#util#do_autocmd', ['CocStatusChange'], true);
             await nvim.resumeNotification(false, true);
@@ -51656,6 +51657,7 @@ class DiagnosticBuffer {
         }
         this.nvim.call('coc#util#set_buf_var', [this.bufnr, 'coc_diagnostic_info', info], true);
         if (bufnr == this.bufnr) {
+            logger.debug("redraws", new Error().stack);
             this.nvim.command('redraws', true);
             this.nvim.call('coc#util#do_autocmd', ['CocDiagnosticChange'], true);
         }
@@ -57962,8 +57964,10 @@ class ListManager {
             cwd: this.cwd,
         };
         buf.setVar('list_status', status, true);
-        if (ui.window)
+        if (ui.window) {
+            logger.debug("redraws", new Error().stack);
             nvim.command('redraws', true);
+        }
     }
     async onInputChar(ch, charmod) {
         let { mode } = this.prompt;
@@ -61374,6 +61378,7 @@ class Worker {
                 let idx = Math.floor((new Date()).getMilliseconds() / 100);
                 nvim.pauseNotification();
                 nvim.setVar('coc_list_loading_status', frames[idx], true);
+                logger.debug("redraws", new Error().stack);
                 nvim.command('redraws', true);
                 nvim.resumeNotification(false, true).logError();
             }, 100);
@@ -61383,6 +61388,7 @@ class Worker {
                 clearInterval(this.interval);
                 nvim.pauseNotification();
                 nvim.setVar('coc_list_loading_status', '', true);
+                logger.debug("redraws", new Error().stack);
                 nvim.command('redraws', true);
                 nvim.resumeNotification(false, true).logError();
             }
```

I will report an issue to vim.

**Comment by wwwjfy** [comment] 2019-11-08 16:26
Yes, I've mentioned above that removing `redraws`, and I also can "fix" it by adding `redrawt` (redraw tabline) right after `redraws`.
However, I could not reproduce it in vim. And `redraws` means redraw statusline. I don't know how this can affect tabline. I now suspect it's a bug in neovim, but not sure about vim itself.

**Comment by yan12125** [comment] 2019-11-08 16:59
Oops, somehow I didn't see your workarounds. And yes, adding `redrawt` is what I'm using.

**Comment by yan12125** [comment] 2019-11-09 03:39
@chemzqm In https://github.com/vim/vim/issues/5195#issuecomment-551930885 a vim developer suggests that `:redraws` upon `BufUnload` is not needed. As @wwwjfy mentioned, removing `redraws` fixed the issue, and the status line is still updated correctly. Could you consider applying the following patch?
```Diff
diff --git a/src/diagnostic/buffer.ts b/src/diagnostic/buffer.ts
index b660a8ad..86badbc8 100644
--- a/src/diagnostic/buffer.ts
+++ b/src/diagnostic/buffer.ts
@@ -162,7 +162,6 @@ export class DiagnosticBuffer implements Disposable {
     }
     this.nvim.call('coc#util#set_buf_var', [this.bufnr, 'coc_diagnostic_info', info], true)
     if (bufnr == this.bufnr) {
-      this.nvim.command('redraws', true)
       this.nvim.call('coc#util#do_autocmd', ['CocDiagnosticChange'], true)
     }
   }
```

**Comment by wwwjfy** [comment] 2019-11-09 15:36
👍 to @yan12125 

I found it was introduced in commit https://github.com/neoclide/coc.nvim/commit/e5804de4a489d7a0c541b3ca325616e76b3648a9, but there is no context what this commit aimed to fix.

I followed the stack. I think we do need to update status line when the diagnostic info change, though in this case `BufUnload`, `clear()` calls `this.setDiagnosticInfo(workspace.bufnr, [])`.
https://github.com/neoclide/coc.nvim/blob/1ff50ec3b060e4c4e6712002d352fdbc746b1b21/src/diagnostic/buffer.ts#L245

The loop in `setDianosticInfo` won't be used because the second parameter is an empty array.
As I tested, this line alone could make sure the status line is updated.
https://github.com/neoclide/coc.nvim/blob/1ff50ec3b060e4c4e6712002d352fdbc746b1b21/src/diagnostic/buffer.ts#L163
So could we just put this line in `clear()` function?

I know very little how coc works. This is no big deal, but a bit annoying in the daily usage.

**Comment by yan12125** [comment] 2019-11-11 11:22
>  So could we just put this line in clear() function?

Sounds a better approach! Hopefully chemzqm or another core developer can reproduce the issue and apply this or some other fix.

> I've reproduced it in macOS 10.14 and 10.15, but not ubuntu 18.04

@wwwjfy Maybe you can find the difference between the two machines and find out why the issue is not always reproducible? I guess that will help developers to reproduce this.

**Comment by wwwjfy** [comment] 2019-11-11 17:42
Sorry, I was wrong. I could reproduce it on Ubuntu too. And it's 100% reproducible.
I'm not sure what's the preferable way to create an environment that can be shared. I could create a virtual machine using VirtualBox if the maintainers are willing to give a try.

**Comment by ohjames** [comment] 2019-11-16 16:42
I get this too. It's 100% reproducible when closing the first tab, and about 20% reproducible when closing the final tab. I'm pretty sure I've seen it with closing "middle" tabs too, but I can't reproduce that right now.

**Comment by ohjames** [comment] 2019-11-16 16:45
BTW I'm using archlinux here. If I remove the `Plug` line for coc the issue goes away. I'm using `NVIM v0.4.2`. It's been happening for about one or two months.

**Closed** 2019-11-17 07:03 UTC
Labels: Can't reproduce
