### ISSUE TITLE
Open specific list from lists failed

### ISSUE THREAD

**Issue by listenerri** [neoclide/coc.nvim#4695] opened 2023-07-03 04:17 UTC
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 9.0 9000749
node version: v18.16.0
coc.nvim version: 0.0.82-b7375d5f 2023-01-30 05:09:03 +0800
coc.nvim directory: /home/ri/ri-vim/vim-plug/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2023-07-03T11:33:05.842 DEBUG (pid:4956) [core-documents] - buffer created 1 true file:///home/ri/ri-vim/vimrc
2023-07-03T11:33:05.847 DEBUG (pid:4956) [core-editors] - editor created winid & bufnr & tabpageid:  1000 1 1
2023-07-03T11:33:05.890 TRACE (pid:4956) [sources] - created service source snippets
2023-07-03T11:33:05.890 TRACE (pid:4956) [sources] - created service source snippets-source
2023-07-03T11:33:05.892 TRACE (pid:4956) [timing] - activate coc-marketplace cost: 15
2023-07-03T11:33:05.892 TRACE (pid:4956) [timing] - activate coc-snippets cost: 10
2023-07-03T11:33:05.893 INFO (pid:4956) [plugin] - coc.nvim initialized with node: v18.16.0 after 135
2023-07-03T11:33:09.837 TRACE (pid:4956) [attach] - Notification autocmd: CursorHold 1 [ 681, 41 ]
2023-07-03T11:33:15.428 INFO (pid:4956) [attach] - receive notification: openLog []
2023-07-03T11:33:15.448 TRACE (pid:4956) [attach] - Notification autocmd: BufWinLeave 1 1000
2023-07-03T11:33:15.448 TRACE (pid:4956) [attach] - Notification autocmd: BufHidden 1
2023-07-03T11:33:15.449 TRACE (pid:4956) [attach] - Notification autocmd: BufCreate 2
2023-07-03T11:33:15.452 TRACE (pid:4956) [attach] - Notification autocmd: BufEnter 2
2023-07-03T11:33:15.458 TRACE (pid:4956) [attach] - Notification autocmd: BufWinEnter 2 1000
2023-07-03T11:33:15.471 DEBUG (pid:4956) [core-documents] - buffer created 2 true file:///run/user/1000/coc-nvim-4956.log
2023-07-03T11:33:15.471 TRACE (pid:4956) [attach] - Notification autocmd: CursorMoved 2 [ 1, 1 ]
2023-07-03T11:33:15.471 TRACE (pid:4956) [attach] - Notification autocmd: WinScrolled 1000
2023-07-03T11:33:15.472 DEBUG (pid:4956) [core-editors] - editor created winid & bufnr & tabpageid:  1000 2 1
2023-07-03T11:33:16.457 TRACE (pid:4956) [attach] - Notification autocmd: VimResized 156 21
2023-07-03T11:33:19.499 TRACE (pid:4956) [attach] - Notification autocmd: CursorHold 2 [ 1, 1 ]
2023-07-03T11:33:19.500 TRACE (pid:4956) [attach] - Notification autocmd: WinScrolled 1000
2023-07-03T11:33:32.550 TRACE (pid:4956) [attach] - Notification autocmd: BufWinLeave 2 1000
2023-07-03T11:33:32.551 TRACE (pid:4956) [attach] - Notification autocmd: BufUnload 2
2023-07-03T11:33:32.551 DEBUG (pid:4956) [core-documents] - document detach 2 file:///run/user/1000/coc-nvim-4956.log
2023-07-03T11:33:32.554 TRACE (pid:4956) [attach] - Notification autocmd: BufEnter 1
2023-07-03T11:33:32.566 TRACE (pid:4956) [attach] - Notification autocmd: BufWinEnter 1 1000
2023-07-03T11:33:32.566 TRACE (pid:4956) [attach] - Notification autocmd: CursorMoved 1 [ 681, 41 ]
2023-07-03T11:33:32.566 TRACE (pid:4956) [attach] - Notification autocmd: WinScrolled 1000
2023-07-03T11:33:32.595 DEBUG (pid:4956) [core-editors] - editor created winid & bufnr & tabpageid:  1000 1 1
2023-07-03T11:33:36.603 TRACE (pid:4956) [attach] - Notification autocmd: CursorHold 1 [ 681, 41 ]
2023-07-03T11:34:37.560 INFO (pid:4956) [attach] - receive notification: openList []
2023-07-03T11:34:37.577 TRACE (pid:4956) [attach] - Notification autocmd: WinLeave 1000
2023-07-03T11:34:37.585 TRACE (pid:4956) [attach] - Notification autocmd: WinEnter 1001
2023-07-03T11:34:37.601 TRACE (pid:4956) [attach] - Notification autocmd: FileType list 3
2023-07-03T11:34:37.603 TRACE (pid:4956) [attach] - Notification autocmd: BufEnter 3
2023-07-03T11:34:37.604 TRACE (pid:4956) [attach] - Notification autocmd: BufWinEnter 3 1001
2023-07-03T11:34:37.604 TRACE (pid:4956) [attach] - Notification autocmd: CursorMoved 3 [ 1, 1 ]
2023-07-03T11:34:37.605 TRACE (pid:4956) [attach] - Notification autocmd: WinScrolled 1001
2023-07-03T11:34:37.638 DEBUG (pid:4956) [core-documents] - buffer created 3 false list:/lists
2023-07-03T11:34:37.638 TRACE (pid:4956) [attach] - Notification autocmd: TextChanged 3 4
2023-07-03T11:34:49.723 TRACE (pid:4956) [attach] - Event:  InputChar list <cr> 0
2023-07-03T11:34:49.726 TRACE (pid:4956) [attach] - Notification autocmd: WinLeave 1001
2023-07-03T11:34:49.736 TRACE (pid:4956) [attach] - Notification autocmd: WinEnter 1000
2023-07-03T11:34:49.739 TRACE (pid:4956) [attach] - Notification autocmd: BufEnter 1
2023-07-03T11:34:49.802 INFO (pid:4956) [attach] - receive notification: openList [ 'commands' ]
2023-07-03T11:34:49.831 TRACE (pid:4956) [attach] - Notification autocmd: WinLeave 1000
2023-07-03T11:34:49.840 TRACE (pid:4956) [attach] - Notification autocmd: WinEnter 1002
2023-07-03T11:34:49.855 TRACE (pid:4956) [attach] - Notification autocmd: FileType list 4
2023-07-03T11:34:49.858 TRACE (pid:4956) [attach] - Notification autocmd: BufEnter 4
2023-07-03T11:34:49.858 TRACE (pid:4956) [attach] - Notification autocmd: BufWinEnter 4 1002
2023-07-03T11:34:49.859 DEBUG (pid:4956) [core-documents] - buffer created 4 false list:/commands
2023-07-03T11:34:49.859 TRACE (pid:4956) [attach] - Notification autocmd: TextChanged 4 4
2023-07-03T11:34:49.959 TRACE (pid:4956) [attach] - Event:  InputChar list <esc> 0
2023-07-03T11:34:49.960 TRACE (pid:4956) [attach] - Notification autocmd: WinLeave 1002
2023-07-03T11:34:49.971 TRACE (pid:4956) [attach] - Notification autocmd: WinEnter 1000
2023-07-03T11:34:49.975 TRACE (pid:4956) [attach] - Notification autocmd: BufEnter 1
2023-07-03T11:34:58.038 TRACE (pid:4956) [attach] - Notification autocmd: CursorHold 1 [ 681, 41 ]
2023-07-03T11:34:58.039 TRACE (pid:4956) [attach] - Notification autocmd: CursorMoved 1 [ 681, 41 ]
2023-07-03T11:34:58.040 DEBUG (pid:4956) [core-documents] - document detach 3 list:/lists
2023-07-03T11:34:58.040 DEBUG (pid:4956) [core-documents] - document detach 4 list:/commands
2023-07-03T11:37:58.825 TRACE (pid:4956) [attach] - Notification autocmd: CursorMoved 1 [ 687, 24 ]
2023-07-03T11:38:02.988 TRACE (pid:4956) [attach] - Notification autocmd: CursorHold 1 [ 687, 24 ]
2023-07-03T11:38:05.310 TRACE (pid:4956) [attach] - Notification autocmd: VimResized 156 20
2023-07-03T11:38:05.568 TRACE (pid:4956) [attach] - Notification autocmd: VimResized 156 17
2023-07-03T11:38:05.837 TRACE (pid:4956) [attach] - Notification autocmd: VimResized 156 13
2023-07-03T11:38:06.087 TRACE (pid:4956) [attach] - Notification autocmd: VimResized 156 9
2023-07-03T11:38:06.109 TRACE (pid:4956) [attach] - Notification autocmd: VimResized 156 8
2023-07-03T11:38:06.448 TRACE (pid:4956) [attach] - Notification autocmd: VimResized 156 7
2023-07-03T11:38:06.697 TRACE (pid:4956) [attach] - Notification autocmd: VimResized 156 6
2023-07-03T11:40:31.409 TRACE (pid:4956) [attach] - Notification autocmd: VimResized 156 42
2023-07-03T11:40:43.461 INFO (pid:4956) [attach] - receive notification: showInfo []
2023-07-03T11:40:43.461 TRACE (pid:4956) [attach] - Notification autocmd: WinScrolled 1000


```

## Describe the bug

When i press `<CR>` in lists to open the selected list, the list appears but disappears immediately, seemingly because it received an abnormal `<Esc>` input char.

Even if I comment out all the configurations in the vimrc and keep only the following, the above failure still occurs:

```
set nocp

call plug#begin('~/.vim/vim-plug')
Plug 'neoclide/coc.nvim', { 'branch': 'release' }
    let $NVIM_COC_LOG_LEVEL = 'trace'
call plug#end()
```

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with (Yes, it can also be reproduced using this configuration)：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.
- :CocList
- Input some chars, e.g. command
- Press `<CR>`

**Comment by fannheyward** [comment] 2023-07-10 02:35
Can't reproduce, upgrade your vim and try again.

**Comment by listenerri** [comment] 2023-07-10 04:06
> Can't reproduce, upgrade your vim and try again.

It can reproduced on Manjaro unstable, with lastest `gvim` package:

```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jul 08 2023 13:06:53)
Included patches: 1-1676
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
```

It works well when using gvim, but it doesn't work well when using vim under the terminal.

**Comment by listenerri** [comment] 2023-07-10 06:21
> Can't reproduce, upgrade your vim and try again.

I made a docker container based on latest ubuntu to reproduce this issue:

Dockerfile:

```
FROM ubuntu:23.04

WORKDIR /root

RUN apt update
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt install -y curl vim-gtk3 git
RUN mkdir .vim && cd .vim && git clone -b release https://github.com/neoclide/coc.nvim.git
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
RUN bash -i -c "nvm install --lts"
RUN echo "set nocompatible \n\
set runtimepath^=/root/.vim/coc.nvim \n\
filetype plugin indent on \n\
syntax on \n\
set hidden" > /root/.vim/vimrc
```

Build the docker image from Dockerfile:

```
docker build -t ubuntu:23.04-coc-test .

# If you need specify proxy server:
docker build -t ubuntu:23.04-coc-test --build-arg=http_proxy="http://192.168.0.100:7890" --build-arg=https_proxy="http://192.168.0.100:7890" .
```

Run the docker container from built image and open vim to reproduce this issue:

```
docker run --rm -it ubuntu:23.04-coc-test bash

vim ~/.vim/vimrc

# In vim
:CocList <CR>
extensions <CR>
# Wait a second, the extentions list disappear/closed
```

Please give it a try, thanks.

**Comment by fannheyward** [comment] 2023-07-10 07:08
Sorry I was testing with _master_, not _release_, yes, reproduced with `release`. This has been fixed in https://github.com/neoclide/coc.nvim/pull/4584, hadn't push to release for now, you can use master branch:

`Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}`

**Closed by fannheyward** 2023-07-10 07:08 UTC
Labels: Can't reproduce

**Comment by fannheyward** [comment] 2023-07-26 14:58
The `release` branch has been upgraded.
