### ISSUE TITLE
Wrong workspace folder URI

### ISSUE THREAD

**Issue by wonnage** [neoclide/coc.nvim#1126] opened 2019-08-29 20:11 UTC
If I start vim outside of my project folder, the file:/// uri for workspace folders is missing the home directory prefix. It results in a crash when trying to open a nonexistent file.

I added a log to print out the URLs that coc-eslint is receiving right before this line: https://github.com/neoclide/coc-eslint/blob/c8f1639146748b46f871144ed471c44741492c97/server/index.ts#L866

Expected:
````
## Output channel: eslint

[Info  - 12:29:16 PM] ESLint server running in node v10.16.0
[Info  - 12:29:17 PM] ESLint library loaded from: /Users/wonnage/workspace/nbreader/node_modules/eslint/lib/api.js
>>> { uri: 'file:///Users/wonnage/workspace/nbreader',
  name: 'nbreader' } <<<
````

Started vim from home folder (cwd = /Users/wonnage)
````
## Output channel: eslint

[Info  - 12:29:36 PM] ESLint server running in node v10.16.0
[Info  - 12:29:37 PM] ESLint library loaded from: /Users/wonnage/workspace/nbreader/node_modules/eslint/lib/api.js
>>> { uri: 'file:///workspace/nbreader/', name: 'nbreader' } <<<
[Error  - 12:29:37 PM] ESLint stack trace:
[Error  - 12:29:37 PM] Error: ENOENT: no such file or directory, chdir '/workspace/nbreader/'
    at process.chdir (internal/process/main_thread_only.js:31:12)
    at validate (/Users/wonnage/.config/coc/extensions/node_modules/coc-eslint/lib/server.js:5509:29)
    at resolveSettings.then.settings (/Users/wonnage/.config/coc/extensions/node_modules/coc-eslint/lib/server.js:5454:13)
````

**Comment by chemzqm** [comment] 2019-09-10 06:45
Can't reproduce.

**Comment by chemzqm** [comment] 2019-09-10 08:27
Should be fixed now, I've made eslint use corrent workspaceFolder depends on uri of file.

**Closed by chemzqm** 2019-09-10 08:27 UTC
Labels: Can't reproduce
