### ISSUE TITLE
coc-style and coc-prettier get conflict

### ISSUE THREAD

**Issue by iamcco** [neoclide/coc.nvim#276] opened 2018-12-16 04:09 UTC
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.

**Describe the bug**

coc-prettier depend on => prettier-stylelint@0.4.2 => stylelint@8.1.1 t=>postcss-html@0.12.0 that get conflict witch coc-vetur

**To Reproduce**

open an vue file `test.vue`

**Screenshots**

<img width="1235" alt="2018-12-16 11 54 47" src="https://user-images.githubusercontent.com/5492542/50049992-48e99580-012b-11e9-8656-f79b0ce2b364.png">

**Comment by chemzqm** [comment] 2018-12-16 12:06
Consider upgrade your yarn and run `:CocUpdate`

**Comment by chemzqm** [comment] 2018-12-16 13:53
Can't reproduce, I need your configuration.

**Comment by iamcco** [comment] 2018-12-16 15:05
if i manually install postcss-html@latest or remove coc-prettier then it works. i thank it's not config's issue. i don't know why it alway install the oldest version of postcss-html

**Comment by chemzqm** [comment] 2018-12-16 15:40
It's problem of coc-stylelint.

**Comment by chemzqm** [comment] 2018-12-16 16:48
It's problem of postcss as peer dependency, fixed with latest coc-stylelint.

**Closed by chemzqm** 2018-12-16 16:48 UTC
Labels: Can't reproduce, question
