### ISSUE TITLE
Among the overloaded functions, how do I see the signature of the function I want?

### ISSUE THREAD

**Issue by zndn1997** [neoclide/coc.nvim#2298] opened 2020-09-02 09:54 UTC
```cpp
class Foo
{
public:
    //...
    int Bar(int a, int b);
    int Bar(double c, int d);
    int Bar(std::string e, char f);
    //...
};

int main()
{
    Foo test;
    test.Bar(); // Always showing 'Bar(std::string d, char e)' function signature.
    // I can't switch to other overloaded functions.
    //...
    return 0;
}
```

If I want to know parameters of `Bar(double c, int d)`, I must input value of double and `,`.

Code Completion alert '+3 overloads', But I can see signature the last one function only.

How can I switching signature information of overload functions?

Please help!

**Comment by oblitum** [comment] 2020-09-02 15:54
Duplicate of #1441.

**Closed by oblitum** 2020-09-02 15:54 UTC

**Comment by zndn1997** [comment] 2020-09-02 21:51
No, It's different.

He can saw overloaded functions list when If he retyping `(`.

But My case, ONLY ONE function can see. CAN'T see overloaded functuons.

If I want to see that, Go to reference and searching same name of function by hand.

**Comment by oblitum** [comment] 2020-09-02 22:13
@zndn1997 it's the same issue, read the issue thread and try the configurations suggested there.

**Comment by zndn1997** [comment] 2020-09-03 00:32
coc.nvim:
<img width="343" alt="capture 1" src="https://user-images.githubusercontent.com/10591275/92051631-e4bba900-edc7-11ea-95fd-c4425a62a758.png">

<img width="320" alt="capture 2" src="https://user-images.githubusercontent.com/10591275/92051692-eb4a2080-edc7-11ea-9383-9b23b24fb3d5.png">

<img width="283" alt="capture 3" src="https://user-images.githubusercontent.com/10591275/92051724-edac7a80-edc7-11ea-8eaf-85b477717b88.png">


VSCode clangd:
<img width="269" alt="capture 4" src="https://user-images.githubusercontent.com/10591275/92051810-f735e280-edc7-11ea-987b-116fb7690763.png">

I'm using same clangd(10.0.0) binary.

I'm already configured this:
<img width="356" alt="capture 5" src="https://user-images.githubusercontent.com/10591275/92052408-424ff580-edc8-11ea-9c87-d79e08aee0c9.png">

**Comment by oblitum** [comment] 2020-09-03 01:16
Can't you read the entire thread?

**Comment by zndn1997** [comment] 2020-09-03 01:30
> Can't you read the entire thread?

I'm read. I don't like clangd compiler option "--completion-style=detailed", But it's the best solution for me when using coc.nvim.
