### ISSUE TITLE
Make `doHover` resolve interface definitions

### ISSUE THREAD

**Issue by bag-man** [neoclide/coc.nvim#1465] opened 2020-01-14 15:48 UTC
I work with Typescript and I can't use `doHover` to see the type definition of an interface, it just shows me `interface Foo`. Which isn't particularly useful, as I already know what the interface is called, I just want to see the definition of it. 

I currently use `jumpDefinition`, to see what the interface is defined as, but that then opens a new buffer and that's frustrating to have to manage. 

If `doHover` could resolve the imported interface that would make life a lot nicer. 

![image](https://user-images.githubusercontent.com/4195057/72358699-44f0c400-36ed-11ea-9377-838131452eb1.png)

```
interface Input {
  foo: string;
}

interface Output {
  bar: string;
}

export const fooFn = (input: Input): Output => ({
  bar: input.foo,
});
```

**Comment by chemzqm** [comment] 2020-01-15 02:57
Duplicate of https://github.com/neoclide/coc-tsserver/issues/109, you may want to create issue for https://github.com/microsoft/TypeScript as well.

**Closed by chemzqm** 2020-01-15 02:57 UTC
