### ISSUE TITLE
Floating window highlighting is incorrect once the window has been used again

### ISSUE THREAD

**Issue by brandoniffert** [neoclide/coc.nvim#1198] opened 2019-09-23 12:37 UTC
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.2
node version: v10.16.0
coc.nvim version: 0.0.74-07b00fd6fc
term: iTerm.app
platform: darwin
```

## Describe the bug

Floating window displays correct highlight groups when you open it for the first time, if you open it again after closing it, incorrect highlight groups are applied. See screenshots.

## Reproduce the bug

- Create file `mini.vim` with：

```vim
set nocompatible
set runtimepath^=/path/to/coc.nvim
filetype plugin indent on
syntax on
set hidden

let g:coc_global_extensions = [
      \ 'coc-tsserver'
      \]

" Use K to show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
```

- Start (neo)vim with command: `nvim -u mini.vim`

- Operate vim.

## Screenshots (optional)

- File is opened for the first time and documentation is shown (using `K` mapping)

<img width="588" alt="Screen Shot 2019-09-23 at 8 20 56 AM" src="https://user-images.githubusercontent.com/160448/65425465-081a5d80-dddc-11e9-81ef-3308ec70eddd.png">

- Cursor moves and documentation goes away, cursor is returned and documentation is shown again with incorrect highlight groups

<img width="587" alt="Screen Shot 2019-09-23 at 8 21 08 AM" src="https://user-images.githubusercontent.com/160448/65425522-28e2b300-dddc-11e9-8228-f6b3c0c87b09.png">

- Did not understand where the weird highlighting groups were coming from, after some playing around I found out it was `SignColumn`, `LineNr`, and `StatusLine` in this case

- After running `:hi! SignColumn guifg=red`

<img width="588" alt="Screen Shot 2019-09-23 at 8 22 15 AM" src="https://user-images.githubusercontent.com/160448/65425614-5f203280-dddc-11e9-8d3a-93f023861e02.png">

- After running `:hi! LineNr guifg=green`

<img width="588" alt="Screen Shot 2019-09-23 at 8 22 35 AM" src="https://user-images.githubusercontent.com/160448/65425629-66dfd700-dddc-11e9-8a3a-ccd5ce70c4cb.png">

- After running `:hi! StatusLine guifg=yellow`

<img width="589" alt="Screen Shot 2019-09-23 at 8 23 36 AM" src="https://user-images.githubusercontent.com/160448/65425671-7d862e00-dddc-11e9-9f52-2eb39c3597da.png">

**Comment by fannheyward** [comment] 2019-09-24 02:26
Can't reproduce.

**Comment by acepukas** [comment] 2019-09-24 22:23
I'm having a very similar issue. In my case, SignColumn is shifting the highlighting over by 2 chars.

![wrong_popup_syntax_highlighting](https://user-images.githubusercontent.com/2087765/65553579-2cb62880-def5-11e9-8a3d-46de93b97007.png)

You can see the darker 2 char span at the beginnings of some lines. That's SignColumn.

I was debugging the src/utils/highlight.ts file and noticed that SignColumn highlight group entries are being added the the `Highlight[]` result array that is resolved by the `getHighlights` function.

After line 153 of [highlight.ts](https://github.com/neoclide/coc.nvim/blob/8130924d40dba2e30972f4cf150f99c653c73070/src/util/highlight.ts#L152) I added

```typescript
if(hlGroup === 'SignColumn') continue
```

to try to ignore the SignColumn group and that worked. The highlighting was no longer at the wrong offset. I'm not suggesting that's the solution, just demonstrating that the highlight groups are the issue.

Things like sign column and line numbers should not be on for those floating buffers.

Within highlight.ts I attempted to append a config option [where other settings are set](https://github.com/neoclide/coc.nvim/blob/8130924d40dba2e30972f4cf150f99c653c73070/src/util/highlight.ts#L175) with

```typescript
['nvim_command', ['set signcolumn=no']],
```

but that didn't do anything.

Then I tried to set it on the buffer like [this line](https://github.com/neoclide/coc.nvim/blob/8130924d40dba2e30972f4cf150f99c653c73070/src/util/highlight.ts#L189):

```typescript
await buf.setOption('signcolumn', 'no')
```

but that didn't take either.

I don't know enough about the neovim api at the moment to troubleshoot further than that.

I should mention that I tested the same scenario without any changes to coc.nvim but with `set signcolumn=no` in my init.vim and that also worked but obviously that isn't ideal either.

**Comment by chemzqm** [comment] 2019-09-25 01:36
I think that your syntax plugin are doing bad things, try use minimal vimrc.

**Comment by acepukas** [comment] 2019-09-25 03:42
@chemzqm you were right. It was a misbehaving syntax highlight plugin I was using for nginx. Oh well.

**Closed** 2019-09-27 10:50 UTC
Labels: Can't reproduce
