### ISSUE TITLE
Doesn`t work with node installed via snap: Error: Node version  < 9.12.0, please upgrade node.js but I have node v16.0.0-nightly20210204fe43bd8ddd

### ISSUE THREAD

**Issue by desmap** [neoclide/coc.nvim#2870] opened 2021-02-04 10:52 UTC
## Result from CocInfo

`Error: Node version  < 9.12.0, please upgrade node.js`

## Reproduce the bug

Install latest node, e.g. via `snap install node --channel=latest/edge --classic`

then check the version

```
$ node -v
v16.0.0-nightly20210204fe43bd8ddd
```

FWIW, my nvim version is `v0.5.0-dev+1064-gb96db38af`

**Comment by fannheyward** [comment] 2021-02-04 10:58
`v16.0.0-nightly20210204fe43bd8ddd` is parsed error, current regex only supports `v16.0.0` format.

**Comment by desmap** [comment] 2021-02-04 11:12
Thanks for the fast response. So, just tried it again and `:CocInfo` gives `Error: Node version  < 10.12.0, please upgrade node.js` this time. Maybe because I installed node via snap?

**Comment by fannheyward** [comment] 2021-02-04 11:18
coc gets empty `node --version`, the error message should be something like this: `Error: Node version 8.0.0 < 10.12.0 ...`.

Try to set node path by `g:coc_node_path`

**Comment by desmap** [comment] 2021-02-04 11:27
Ok:
```
$ which node
/snap/bin/node
```
I added this as the first line of my `init.vim`:
```
let g:coc_node_path = '/snap/bin/node'
```
and get again
```
Error: Node version  < 10.12.0, please upgrade node.js
```
strange....

**Comment by fannheyward** [comment] 2021-02-04 11:31
@desmap add `echomsg output` bellow `path/to/your/coc.nvim/plugin/coc.nvim` line 399:

```
      let output = trim(system(node . ' --version'))
      echomsg output
```

**Comment by desmap** [comment] 2021-02-04 11:42
added `echomsg output` after that line, restarted nvim, did `:CocInfo` and got:
```
coc.nvim service not started, checking environment...

Press ENTER or type command to continue
```
Once I press Enter I get again:
```
Error: Node version  < 10.12.0, please upgrade node.js
```

**Comment by fannheyward** [comment] 2021-02-04 11:43
Your output is empty, add `echomsg node` before the line and try again.

**Comment by desmap** [comment] 2021-02-04 11:45
done, I've got:
```
coc.nvim service not started, checking environment...
/snap/bin/node

Press ENTER or type command to continue
```

**Comment by fannheyward** [comment] 2021-02-04 11:51
Try `:echo system('/snap/bin/node' . ' --version')`, what's the output?

**Comment by fannheyward** [comment] 2021-02-04 11:53
Looks like it's caused by node installed from snap, https://github.com/neoclide/coc.nvim/issues/1830

**Comment by desmap** [comment] 2021-02-04 11:54
nothing in nvim and when in Bash:
```
$ /snap/bin/node --version
v16.0.0-nightly20210204fe43bd8ddd
```

**Comment by desmap** [comment] 2021-02-04 11:56
how snap manages the bins is strange, look:
```
$ sudo ls -l /snap/bin
...
lrwxrwxrwx 1 root root 13 Feb  4 11:24 node -> /usr/bin/snap
...
```

**Comment by desmap** [comment] 2021-02-04 11:57
and the link leads to...
```
$ ls /usr/bin/snap -l
-rwxr-xr-x 1 root root 23586096 Nov 19 17:51 /usr/bin/snap
```

**Comment by fannheyward** [comment] 2021-02-04 12:00
> nothing in nvim

It should echo node version. Have no idea about this, I don't use snap.

**Comment by desmap** [comment] 2021-02-04 12:01
Ok, I've just your reference to the other issue, ok then I guess I can't install nvim with snap... sad because snap provides nvim on edge + it is updating nvim

**Comment by desmap** [comment] 2021-02-04 12:05
However, thanks for your support and fast replies, FWIW I just changed the title.

**Comment by fannheyward** [comment] 2021-02-04 12:08
Close it because this issue is not on coc side.

**Closed by fannheyward** 2021-02-04 12:08 UTC
