### ISSUE TITLE
Uncaught exception: Header must provide a Content-Length property for SQL type files

### ISSUE THREAD

**Issue by mortymacs** [neoclide/coc.nvim#4343] opened 2022-11-05 09:45 UTC
## Result from CocInfo

```
vim version: NVIM v0.8.0
node version: v19.0.1
coc.nvim version: 0.0.82-eda26e65 2022-11-05 14:47:34 +0800
coc.nvim directory: /home/mort/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux
```

## Describe the bug

I configured my cocvim for SQL files by official [config](https://github.com/neoclide/coc.nvim/wiki/Language-servers#sql)
In any SQL file, it will raise this error:

```
[coc.nvim]: Uncaught exception: Header must provide a Content-Length property.
Uncaught exception: Header must provide a Content-Length property.
```

## Reproduce the bug

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=~/.vim/plugged/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"
  inoremap <silent><expr> <c-space> coc#refresh()
  ```

- Start (neo)vim with command: `nvim -u mini.vim db.sql`

- Operate vim.

  Try to get auto-completion (e.g. `CREATE` statement) by ctrl-space, and you'll get nothing.
  Then check `:CocInfo`, there you'll see the error.

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/1261448/200113554-bf345a81-0c4c-41a8-9208-0a5225e17bc0.png)

**Comment by chemzqm** [comment] 2022-11-05 10:33
Duplicate of #3912, what's configuration you're using for sql language server?

**Closed by chemzqm** 2022-11-05 10:33 UTC

**Comment by mortymacs** [comment] 2022-11-05 10:45
I'm using the default one:
```json
{
  "languageserver": {
    "sql": {
      "command": "sql-language-server",
      "args": ["up", "--method", "stdio"],
      "filetypes": ["sql", "db"]
    }
}
```

**Comment by chemzqm** [comment] 2022-11-05 12:27
The language server uses `console.log` that breaks stdio.
Use node ipc instead:
```json
     // "command": "sql-language-server",
      "module": "/path/to/sql-language-server/dist/bin/cli.js",
      "args": ["up", "--method", "node-ipc"],
```

**Comment by mortymacs** [comment] 2022-11-05 12:37
Thank you!
