### ISSUE TITLE
Markdown in documentation preview window not rendering

### ISSUE THREAD

**Issue by kkoomen** [neoclide/coc.nvim#1049] opened 2019-07-31 07:45 UTC
## Describe the bug

The preview window showing documentation is not rendering the markdown as it should.

## Reproduce the bug

- Type `var_dump` and select the `var_dump` in the suggestion menu.
- The preview window pops up with documentation about `var_dump`
- See result (markdown not rendered)

## Screenshots (optional)

**Current result**
<img width="1617" alt="Screenshot 2019-07-31 at 15 39 30" src="https://user-images.githubusercontent.com/10693490/62193290-0ae36e00-b3aa-11e9-9b10-db1b5fe013af.png">

**Expected result**

<img width="557" alt="Screenshot 2019-07-31 at 15 41 02" src="https://user-images.githubusercontent.com/10693490/62193294-0cad3180-b3aa-11e9-84b9-868cd7c2635c.png">

**Comment by chemzqm** [comment] 2019-07-31 07:49
Need output from langauge server https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by kkoomen** [comment] 2019-07-31 13:01
This is the output of phpls, obtained `:CocCommand workspace.showOutput`
```
[Info  - 8:56:15 PM] Initialising intelephense 1.1.5
[Info  - 8:56:15 PM] Reading state from /Users/koomen/.config/coc/extensions/coc-phpls-data/508ac52f.
[Info  - 8:56:16 PM] Initialised in 612 ms
[Info  - 8:56:16 PM] Intelephense 1.0.14
[Info  - 8:56:16 PM] {
    "name": "initialised",
    "properties": {
        "version": "1.1.5",
        "machineId": "9cf5a046df97d5db162f8266e095580fdc71a93f177230832534abde144ac7d6",
        "platform": "darwin",
        "clientName": "unknown"
    }
}
[Info  - 8:56:17 PM] Indexing started.
[Info  - 8:56:17 PM] Indexing ended. 2 files indexed in 0s.
[Info  - 8:56:17 PM] Writing state to /Users/koomen/.config/coc/extensions/coc-phpls-data/508ac52f.
[Info  - 8:56:18 PM] Wrote state in 0.6s.
```

<hr />

The same is for the 2nd preview window that appeared for me:

<img width="433" alt="Screenshot 2019-07-31 at 20 58 37" src="https://user-images.githubusercontent.com/10693490/62213796-50b62b80-b3d6-11e9-885c-67289a6b2ac6.png">

**Comment by kkoomen** [comment] 2019-07-31 13:03
Here's output from `:CocInfo`

```
vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  8 2019 19:24:38)
node version: v12.6.0
coc.nvim version: 0.0.73-f283b585e3
term: iTerm.app
platform: darwin
```

**Comment by chemzqm** [comment] 2019-07-31 14:13
duplicate of，#959

**Closed by chemzqm** 2019-07-31 14:13 UTC
Labels: Can't reproduce, question
