### ISSUE TITLE
Missing $-signs in floating windows

### ISSUE THREAD

**Issue by noughtmare** [neoclide/coc.nvim#3432] opened 2021-10-16 18:04 UTC
## Result from CocInfo

```
## versions

vim version: NVIM v0.4.4
node version: v14.17.6
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /home/user/.vim/pack/coc/start/coc.nvim
term: xterm-kitty
platform: linux

## Log of coc.nvim

2021-10-16T19:43:09.904 INFO (pid:38390) [services] - registered service "languageserver.haskell"
2021-10-16T19:43:09.909 INFO (pid:38390) [services] - haskell state change: stopped => starting
2021-10-16T19:43:09.911 INFO (pid:38390) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v14.17.6 after 56ms
2021-10-16T19:43:09.916 INFO (pid:38390) [language-client-index] - Language server "languageserver.haskell" started with 38401
2021-10-16T19:43:10.078 INFO (pid:38390) [services] - haskell state change: starting => running
2021-10-16T19:43:10.084 INFO (pid:38390) [services] - service languageserver.haskell started
2021-10-16T19:43:12.418 INFO (pid:38390) [attach] - receive notification: showInfo []
```

## Describe the bug

One `$` gets removed from a sequence of `$` signs in floating windows.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Install the Haskell language server version 1.4.0 ([instructions here](https://haskell-language-server.readthedocs.io/en/latest/installation.html); I recommend using [ghcup](https://www.haskell.org/ghcup/))

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Add the following CocConfig:
  ```json
  {
    "languageserver": {
      "haskell": {
        "command": "haskell-language-server-wrapper",
        "args": [
          "--lsp"
        ],
        "rootPatterns": [
          "*.cabal",
          "stack.yaml",
          "cabal.project",
          "package.yaml",
          "hie.yaml"
        ],
        "filetypes": [
          "haskell",
          "lhaskell"
        ]
      }
    }
  }
  ```

- Edit a file with the following content:
  ```haskell
  ($$) = undefined

  test1 a b c d = a $$ (b $ c d)

  test2 = "$$$" + 1
  ```

The Haskell Language Server will give the hint that you can reorder the right hand side of `test1` to avoid parentheses, if you hover over it a floating window will show up with the contents:

```
[hlint refact:Move brackets to avoid $] [I] Move brackets to avoid $
Found:
  a $ (b $ c d)
Why not:
  a $ b (c d)
```

That should be: `Found: a $$ (b $ c d)` and `Why not: a $$ b (c d)`.

Additionally, there is a type error in the right hand side of `test2`, hovering over it will show a floating window with the content:

```
[typecheck -Wdeferred-type-errors] [E] • No instance for (Num [Char]) arising
from a use of ‘+’
• In the expression: "$$" + 1
  In an equation for ‘test2’: test2 = "$$" + 1
```

That should be `In the expression: "$$$" + 1` and `... test2 = "$$$" + 1`.

I have confirmed that this does not happen in visual studio code. And it happens in both vim and neovim.

I believe it should be possible to reproduce this with other language servers (because it also works with the same language server on VSCode), but this is the only one I use.

## Screenshots

![image](https://user-images.githubusercontent.com/2665074/137597625-f9c7ebe2-6066-484a-965d-718b8f2a8bf5.png)

![image](https://user-images.githubusercontent.com/2665074/137597637-535eb760-57c6-4974-b19e-31c150edd714.png)

VSCode:

![image](https://user-images.githubusercontent.com/2665074/137597655-b8563af9-1264-4275-ba22-f06d2d607343.png)

![image](https://user-images.githubusercontent.com/2665074/137597674-c3620a76-d1fc-44e4-8798-7f08f8f6d014.png)

**Comment by fannheyward** [comment] 2021-11-03 11:16
Close this for now, post the logs here and I'll look into it.

**Comment by noughtmare** [comment] 2021-11-03 19:43
Sorry, I forgot. Here's my log:

[log.txt](https://github.com/neoclide/coc.nvim/files/7470273/log.txt)

**Comment by fannheyward** [comment] 2021-11-16 10:46
coc.nvim will format the diagnostic message with a format, by default it's 

https://github.com/neoclide/coc.nvim/blob/19a630de325ed71e153e8ca89f114b040c878b1b/data/schema.json#L725-L729

coc.nvim will replace the format:

https://github.com/neoclide/coc.nvim/blob/19a630de325ed71e153e8ca89f114b040c878b1b/src/diagnostic/manager.ts#L455

The problem is that, when you do `str.replace` in JS with `$$`, the result is unexpected. You can do this test:

1. launch node in your terminal `node`
2. `let format = 'Hi %message'`
3. `format.replace('%message', 'a $$ b')`
4. you'll get `'Hi a $ b'`

The two `$$` will became single $ https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_a_parameter

**Comment by noughtmare** [comment] 2021-11-16 11:29
Good catch!

Would it make sense to do what [this stackoverflow answer](https://stackoverflow.com/a/59697678) suggests? E.g.:

```js
> format.replace('%message', function() {return 'a $$ b'})
'Hi a $$ b'
```

**Closed** 2021-12-22 14:14 UTC
