### ISSUE TITLE
custom lsp completion item icon

### ISSUE THREAD

**Issue by qianxi0410** [neoclide/coc.nvim#3661] opened 2022-02-21 00:57 UTC
In another nvim completion plugin, you can customize your lsp kind of icons like:
![图片](https://user-images.githubusercontent.com/55543743/154872705-1ed00cfb-faec-43cc-8b1f-ef249cd0e190.png)
But in coc, there is no way to do this:
![图片](https://user-images.githubusercontent.com/55543743/154872784-7345bf38-91e1-48ff-972a-8114169c443d.png)
Is it possible to provide users with such an option to customize the lsp icon, which will make the completion entry look more beautiful and straightforward.

**Comment by yaegassy** [comment] 2022-02-21 01:13
duplicate of https://github.com/neoclide/coc.nvim/issues/3568

**Closed** 2022-02-21 01:18 UTC

**Comment by fannheyward** [comment] 2022-02-21 01:58
You can custom completion item labels by kind, checkout `:helpgrep suggest.completionItemKindLabels`.

**Comment by qianxi0410** [comment] 2022-02-21 03:45
thx :D @fannheyward

**Comment by Frederick888** [comment] 2022-07-23 14:42
Just wanna drop a note that if you use the example `completionItemKindLabels`, you may want to disable right-to-left text for your terminal.

The `struct` symbol 0xFB44 is a Hebrew letter and Hebrew is RTL. So in a terminal that handles RTL (Kitty is the only one I found to support this) it looks like:

![image](https://user-images.githubusercontent.com/4507647/180609758-d17a2d4d-80f4-4513-b269-d33c6fb6a38f.png)

And it can mess up your text if you use `pumblend`:

![image](https://user-images.githubusercontent.com/4507647/180609778-fe43cafc-0841-4f3f-8d13-2740986a0fdb.png)

You can disable RTL in Kitty with `force_ltr yes`. Or simply replace it with a different symbol. Replacing the double column ones (`event`, `field`, `reference`) is also a good idea.
