### ISSUE TITLE
E967: text property info corrupted

### ISSUE THREAD

**Issue by kkoomen** [neoclide/coc.nvim#1048] opened 2019-07-31 03:29 UTC
## Result from CocInfo

```
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  8 2019 19:24:38)
node version: v12.6.0
coc.nvim version: 0.0.73-07a84965f1
term: iTerm.app
platform: darwin

## Messages
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"test.php" 6L, 144C
## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
fatal: not a git repository (or any of the parent directories): .git

Error 128 on: 'git rev-parse --show-toplevel' in /Users/koomen
fatal: not a git repository (or any of the parent directories): .git
resolved root: null
resolved root: null

## Output channel: highlight

[Info  - 11:30:15 AM] Highlight server running in node v12.6.0

## Output channel: phpls

[Info  - 11:30:16 AM] Initialising intelephense 1.1.5
[Info  - 11:30:16 AM] Reading state from /Users/koomen/.config/coc/extensions/coc-phpls-data/75877ae5.
[Info  - 11:30:16 AM] Initialised in 17 ms
[Info  - 11:30:16 AM] Intelephense 1.0.14
[Info  - 11:30:16 AM] {
    "name": "initialised",
    "properties": {
        "version": "1.1.5",
        "machineId": "9cf5a046df97d5db162f8266e095580fdc71a93f177230832534abde144ac7d6",
        "platform": "darwin",
        "clientName": "unknown"
    }
}
[Info  - 11:30:16 AM] Indexing started.
[Info  - 11:30:18 AM] Indexing ended. 98 files indexed in 1s.

## Output channel: watchman



```

## Describe the bug

When I use `<Tab>` it keeps giving me the error  `E967: text property info corrupted` every moment when my cursor moves.

## Reproduce the bug

1) Open `test.php` with:

```php
<?php

public function updateSubscriptions($args = array()) {
  if ($subscribed_to_newsletter = request($args, 'subscribe_to_newsletter')) {
// cursor here
  }
}
```

2) Have your cursor at line 5 starting at column 0 and press `<Tab>`

3) See error (note: can't reproduce this error with minimal vimrc)

## Additional info

These are my plugs (maybe you know if there is a conflict)
```
Plug 'AndrewRadev/splitjoin.vim'
Plug 'Yggdroot/indentLine'
Plug 'alvan/vim-closetag'
Plug 'editorconfig/editorconfig-vim'
Plug 'godlygeek/tabular'
Plug 'jiangmiao/auto-pairs'
Plug 'joshdick/onedark.vim', { 'dir': '~/.vim/pack/vendor/opt/onedark' }
Plug 'junegunn/fzf.vim'
Plug 'junegunn/vader.vim'
Plug 'ludovicchabant/vim-gutentags'
Plug 'mileszs/ack.vim'
Plug 'neoclide/coc-neco'
Plug 'neoclide/coc-sources'
Plug 'neoclide/coc.nvim', { 'branch': 'release' }
Plug 'sheerun/vim-polyglot'
Plug 'sickill/vim-pasta'
Plug 'tomtom/tcomment_vim'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'yegappan/mru'
```

## Screenshots (optional)

<img width="350" alt="Screenshot 2019-07-31 at 11 12 27" src="https://user-images.githubusercontent.com/10693490/62181813-1ffad580-b387-11e9-809e-ae14c13c3567.png">

**Comment by chemzqm** [comment] 2019-07-31 05:37
Sorry, I don't have time to figure it out.

**Comment by kkoomen** [comment] 2019-07-31 15:40
I've found the issue. The `foldmethod=marker` + `let &l:softtabstop = 2` in combination with the diagnostics functionality is breaking the plugin.

The `let &l:softtabstop = 2` is done by editorconfig-vim, see [here](https://github.com/editorconfig/editorconfig-vim/blob/master/plugin/editorconfig.vim#L306).

**To reproduce:**
-  Create a temp vimrc: `test.vim` (this is the default coc.nvim example + `foldmethod=marker`):

    ```vim
    set nocompatible
    set runtimepath^=/path/to/coc.nvim
    filetype plugin indent on
    syntax on
    set hidden
    
    " This will give the error
    set foldmethod=marker
    let &l:softtabstop = 2
    ```

- Open `test.php`
- Go into insert mode
- Write the following:

    ```php
    <?php
    $test' // <--- note the apostrophe to create an error
    ```

- Press ESC to go back into normal mode, wait for line 2 to get an error sign.
- Go back into insert mode and press `<Tab>` twice (or more)
- Error appears: `E967: text property info corrupted`

**Comment by chemzqm** [comment] 2019-07-31 16:17
Should be bug of vim, try build vim on master branch

**Comment by kkoomen** [comment] 2019-08-01 01:24
I didn't build vim from the master branch, but did upgrade to a higher version of vim via brew:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 16 2019 03:25:28)
macOS version
Included patches: 1-1700
Compiled by Homebrew
```

and the error still occurs.

**Comment by chemzqm** [comment] 2019-08-01 01:32
I tried your vimrc but can't reproduce. What's your CocConfig?

**Comment by kkoomen** [comment] 2019-08-01 01:51
> What's your CocConfig?

It's empty for now.

Which version of vim are you using?

**Comment by chemzqm** [comment] 2019-08-01 01:53
I tried vim 8.1.1700.

**Comment by kkoomen** [comment] 2019-08-01 01:56
How did you try out that version? Compile locally? Or use a docker?

**Comment by chemzqm** [comment] 2019-08-01 01:59
Compiled on my Mac.

**Comment by kkoomen** [comment] 2019-08-01 02:08
I just removed everything from my local vim so the only thing I'm using now is _literally_ the vimrc I described and still can reproduce the error.

**Comment by cyniczhi** [comment] 2019-08-06 07:46
> I tried vim 8.1.1700.

I met the same issue with this version of Vim, built by home brew on my mac.

**Comment by crmtestresco** [comment] 2019-09-11 08:15
I can confirm similar (the same) behavior editing Typescript files. I did a bit of investigation and believe that this configuration is causing the issue:

```vim
set tabstop=4
set softtabstop=0
set noexpandtab
set shiftwidth=8
```

or similarly this one:

```vim
set tabstop=8
set softtabstop=0
set noexpandtab
set shiftwidth=4
```

See the discrepancy in `tabstop` size vs `shiftwidth` size.

I can reproduce this behavior on as small example as this:

```typescript
module test {
}
```

going to 1st line, hitting `o` and hitting `<tab>` twice. Things go haywire. I see in Vim command line:

```
E967: text property infor corrupted
Press ENTER or type command to continue
```

Pressing any other key then `<Esc>` makes things only worse.

Note: this strange configuration I sometimes end up with is because I am using vim-sleuth and some of the files I edit have unfortunately mixed indentation.

Thank you for creating this beautiful plugin. It is a great piece of software

**Comment by magicalbanana** [comment] 2019-09-16 21:31
Any fix for this? I can confirm this happens only with `go files` (for me anyway).

**Comment by chemzqm** [comment] 2019-09-17 01:18
@magicalbanana no idea what's going wrong, looks like bug of vim.

**Comment by kkoomen** [comment] 2019-09-17 01:48
I updated recently from 8.1.1700 to 8.1.1850 and it seems to be fixed. If it occurs again under any circumstances I will request to reopen the issue. Thanks for now.

**Comment by kkoomen** [comment] 2019-09-17 03:25
Issue still persist as described. Reopening issue.

**Comment by arcnmx** [comment] 2019-10-09 03:14
Am encountering this pretty frequently while editing rust code, 8.1.1967. I have no weird indent settings that I'm aware of but it does seem to be specifically caused by an interaction with code folding in my case: the issues occur while I have `:set foldmethod=syntax`, buy `set foldmethod=manual` appears to make the problem go away for the examples I've found.

**Comment by chemzqm** [comment] 2019-10-09 03:34
Seems `set foldmethod=syntax` causing the issue,  I can't see anything we can do to avoid this error since try catch doesn't work.

**Comment by fannheyward** [comment] 2020-01-18 05:26
https://github.com/vim/vim/issues/5454

> Please check if patch 8.2.0109 fixes this.

It's vim's issue, and looks like been fixed. Close this issue now.

**Closed by fannheyward** 2020-01-18 05:26 UTC
Labels: Can't reproduce, help wanted

**Comment by jpmor** [comment] 2020-01-24 22:07
Unsetting `sts` resolved for me
