### ISSUE TITLE
install opens a new tab(not an issue)

### ISSUE THREAD

**Issue by DONofDESTROY** [neoclide/coc.nvim#2183] opened 2020-07-18 15:26 UTC
**this is not a issue**

Hi everyone, 
Today I updated coc.nvim plug got some errors and fixed them but 
idk why if I try to install new extension it opens a new tab

![image](https://user-images.githubusercontent.com/47606472/87855959-6e5b0880-c939-11ea-9e12-62cf106a518f.png)
is it possible to switch back to installation indication in the status line (the extension loading is indicated in the status line)
![image](https://user-images.githubusercontent.com/47606472/87856059-f80ad600-c939-11ea-8679-91318d6f8a97.png)

**Comment by oblitum** [comment] 2020-07-18 16:51
Duplicate of  #2171.

**Closed by oblitum** 2020-07-18 16:51 UTC

**Comment by chemzqm** [comment] 2020-07-18 19:46
The good thing with spilt window is you know the exact update status and you're unlikely to exit vim which pissiblly cause invalid extension state.
Simply close the window or avoid update too often if you think it's annoying
