### ISSUE TITLE
signature help not showing arguments

### ISSUE THREAD

**Issue by felixge** [neoclide/coc.nvim#1035] opened 2019-07-29 08:13 UTC
## Result from CocInfo

```
## versions

vim version: NVIM v0.3.8
node version: v10.11.0
coc.nvim version: 0.0.73
term: iTerm.app
platform: darwin

## Messages
```

## Describe the bug

The signature help only shows the function name but none of the arguments. If I type a comma, the argument list appears.

![out](https://user-images.githubusercontent.com/15000/62032363-c01af800-b1e9-11e9-8be6-024ae2cbe6b1.gif)

## Reproduce the bug

  ```vim
call plug#begin()
Plug 'neoclide/coc.nvim', {'do': 'yarn install --frozen-lockfile'}
call plug#end()
set cmdheight=2
```

```json
cat ~/.config/nvim/coc-settings.json
{
  "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"]
    }
  }
}
```

Then follow the gif above.

## Screenshots (optional)

<img width="778" alt="Screenshot 2019-07-29 at 10 12 15" src="https://user-images.githubusercontent.com/15000/62032226-74684e80-b1e9-11e9-88e7-4f704dd4fed6.png">
<img width="778" alt="Screenshot 2019-07-29 at 10 12 21" src="https://user-images.githubusercontent.com/15000/62032227-74684e80-b1e9-11e9-97a7-cdabb3b23dab.png">

**Comment by chemzqm** [comment] 2019-07-29 08:16
It's want returned from language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by oblitum** [comment] 2019-07-29 08:18
This is gopls bug. They don't provide correct arguments if you let parenthesis open. If you expand snippet for the method, which will bring a pair of `()` with cursor inside, then it will work.

**Comment by felixge** [comment] 2019-07-29 08:23
@chemzqm https://gh.apple.com/gist/felixge/fb06d8d3f3f3a1699f0d3361d6c21d1e

@oblitum oh, ok. Has this bug been reported to gopls?

**Comment by oblitum** [comment] 2019-07-29 08:23
You can check this by expanding snippet of leaving a closing `)` in front where you'll  type the function until you reach the opening `(`, so that you have a closing `)` already when signature shows up, which should behave differently, and as expected, in my experience.

Related issue: https://github.com/saibing/bingo/issues/20

**Comment by oblitum** [comment] 2019-07-29 08:24
@oblitum I never reported it to gopls, it was fixed in bingo, which got dead by now.

**Comment by felixge** [comment] 2019-07-29 08:26
@oblitum ok. Will close this issue now since it doesn't seem to belong here.

With bingo being dead, what's your current workaround? Just always expanding?

**Comment by oblitum** [comment] 2019-07-29 08:30
> With bingo being dead, what's your current workaround? Just always expanding?

Yes :-/

Which I don't like much, but I didn't bother creating an account on whatever issue tracker they use just to report this, which I think would be low priority and who knows when fixed.

If you have an account in their issue tracker, feel free to report.

**Comment by oblitum** [comment] 2019-07-29 08:33
I got bit butthurt too since it was annoying for it to get fixed on bingo just get an exact regression a few weeks later.

**Closed** 2019-07-29 09:56 UTC
