### ISSUE TITLE
Support WorkDoneProgress messages

### ISSUE THREAD

**Issue by expipiplus1** [neoclide/coc.nvim#1582] opened 2020-02-24 14:16 UTC
**Is your feature request related to a problem? Please describe.**

It's sometimes nice to know where the LSP server is in loading a project. In vscode when loading a project there is a little spinning wheel and some diagnostic text from the LSP server at the bottom of the window. These are implemented by the WorkDoneProgress messages from LSP 3.15

**Describe the solution you'd like**

For coc.nvim to request the same diagnostic messages from the LSP server as vscode does and to display these to the user, spinning wheel optional :)

Possible duplicate of #360, but now this feature is part of the standard.

![Screenshot from 2020-02-24 21-54-32](https://user-images.githubusercontent.com/857308/75158166-85157e80-5750-11ea-91f5-9cc2043618fd.png)

**Comment by fannheyward** [comment] 2020-03-10 14:32
coc.nvim 0.0.76 has released with WorkDoneProgress support. You need an extension to registe progress support with token, for example [coc-rust-analyzer rustAnalyzer/cargoWatcher](https://github.com/fannheyward/coc-rust-analyzer/blob/e81d73c1d51fd28bd4df381076769a57b319d68b/src/status_display.ts#L56).

**Closed by fannheyward** 2020-03-10 14:32 UTC
Labels: enhancement

**Comment by expipiplus1** [comment] 2020-03-10 17:12
@fannheyward Thanks, this is great to see working in vim. I added support to the Haskell plugin: https://github.com/expipiplus1/vscode-hie-server/commit/37eb1a04dca3f1b67814c179dcbfb2d2673b0e7b 

If you could spare 5 minutes it would be super for you to have a look at my change to see if it's sensible (I honestly have no idea what I'm doing in typescript, so I hope this is sensible. I mainly ripped it from the rust-analyzer you linked).

The coc.nvim log does show an error on startup, but it still seems to function ok :/

```
2020-03-11T01:04:19.545 INFO (pid:32070) [services] - registered service "languageserver.clangd"
2020-03-11T01:04:19.559 INFO (pid:32070) [plugin] - coc 0.0.76-983e11718a initialized with node: v10.19.0
2020-03-11T01:04:19.565 INFO (pid:32070) [services] - registered service "Haskell HIE (generate-new)"
2020-03-11T01:04:19.566 INFO (pid:32070) [services] - Haskell HIE (generate-new) state change: stopped => starting
2020-03-11T01:04:19.567 ERROR (pid:32070) [extension-vscode-hie-server] - Error: Language client is not ready yet
    at LanguageClient.onProgress (/nix/store/6n1c9w7iyq0rmgiqa67sfpxfh2l4xzhw-vimplugin-coc-nvim-2020-01-05/share/vim-plugins/coc-nvim/build/index.js:57675:19)
    at /nix/store/9hl9jz80m8bypgski6k01z842z1mhwlx-vscode-hie-server/dist/extension.js:1:27693
    at /nix/store/9hl9jz80m8bypgski6k01z842z1mhwlx-vscode-hie-server/dist/extension.js:1:27796
    at Generator.next (<anonymous>)
    at s (/nix/store/9hl9jz80m8bypgski6k01z842z1mhwlx-vscode-hie-server/dist/extension.js:1:23963)
2020-03-11T01:04:19.571 INFO (pid:32070) [language-client-index] - Haskell HIE (generate-new) started with 32124
2020-03-11T01:04:21.819 INFO (pid:32070) [services] - Haskell HIE (generate-new) state change: starting => running
2020-03-11T01:04:21.824 INFO (pid:32070) [services] - service Haskell HIE (generate-new) started
```

**Comment by oblitum** [comment] 2020-03-10 17:15
@expipiplus1 did you list your plugin on the wiki? If not you should, otherwise ppl may have a hard time finding it, as GitHub search doesn't display forked projects.

**Comment by expipiplus1** [comment] 2020-03-10 17:16
One bug I just noticed is that the progress goes from 0% to 1% instead of 100%

Here is my project about half way loaded.

![image](https://user-images.githubusercontent.com/857308/76339871-a754f200-6335-11ea-84b8-87080741960e.png)

**Comment by expipiplus1** [comment] 2020-03-10 17:17
Oh, one other thing: Since this is in the lsp specification. Wouldn't it make sense for coc.nvim to handle this instead of individual plugins? 

- vscode handles this without explicit plugin support
- each plugin for coc.nvim is going to have to implement this very similar code, I feel that this duplication could be avoided by putting it in coc.nvim itself.

**Comment by expipiplus1** [comment] 2020-03-10 17:19
> @expipiplus1 did you list your plugin on the wiki? If not you should, otherwise ppl may have a hard time finding it, as GitHub search doesn't display forked projects.

I haven't yet, but probably should. At the moment I think I'm the only person using this and I don't know if it's "production ready". In fact I don't even know how to package it so that it works in a standard coc.nvim setup.

**Comment by fannheyward** [comment] 2020-03-11 01:31
@expipiplus1 

> Language client is not ready yet

client is not ready when you do `client.onProgress`, current status is starting, not running. You should wait for client ready.

> the progress goes from 0% to 1% instead of 100%

What is the server returns progress number? coc.nvim just add `%` to the number https://github.com/neoclide/coc.nvim/blob/master/src/language-client/progressPart.ts#L49

> each plugin for coc.nvim is going to have to implement this very similar code, I feel that this duplication could be avoided by putting it in coc.nvim itself.

I'm trying to do progress reporting in coc.nvim, the problem is that server needs a `token` to register progress, in your case, `hie` is the token string https://github.com/expipiplus1/vscode-hie-server/commit/37eb1a04dca3f1b67814c179dcbfb2d2673b0e7b#diff-45327f86d4438556066de133327f4ca2R207 .

**Comment by expipiplus1** [comment] 2020-03-11 02:58
> @expipiplus1
> 
> > Language client is not ready yet
> 
> client is not ready when you do `client.onProgress`, current status is starting, not running. You should wait for client ready.

Thanks, I'll see if I can implement that.

> > the progress goes from 0% to 1% instead of 100%
> 
> What is the server returns progress number? coc.nvim just add `%` to the number https://github.com/neoclide/coc.nvim/blob/master/src/language-client/progressPart.ts#L49

According to the specification you are right :). the server should return a value in [0..100]. https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workDoneProgressBegin This looks like a bug in HIE.

> > each plugin for coc.nvim is going to have to implement this very similar code, I feel that this duplication could be avoided by putting it in coc.nvim itself.
> 
> I'm trying to do progress reporting in coc.nvim, the problem is that server needs a `token` to register progress, in your case, [hie](https://github.com/expipiplus1/vscode-hie-server/commit/37eb1a04dca3f1b67814c179dcbfb2d2673b0e7b#diff-45327f86d4438556066de133327f4ca2R207) is the token string, for rust-analyzer, [rustAnalyzer/cargoWatcher](https://github.com/fannheyward/coc-rust-analyzer/blob/e81d73c1d51fd28bd4df381076769a57b319d68b/src/status_display.ts#L56) it the token, coc.nvim doesn't known the token that server needed.

Do you know how vscode does this?

For my example it seems as though any string there will work!

Looking at the log it seems like token is created on the fly for each begin/end pair (`2` in this case)

```
2020-03-11 10:37:32.140644454 [ThreadId 5] - <--2--{"jsonrpc":"2.0","params":{"uri":"file:///home/j/projects/bugs/reload/src/Foo.hs","diagnostics":[]},"method":"textDocument/publishDiagnostics"}
2020-03-11 10:37:32.140730671 [ThreadId 5] - <--2--{"jsonrpc":"2.0","params":{"token":2},"method":"window/workDoneProgress/create","id":2}
2020-03-11 10:37:32.140772046 [ThreadId 5] - <--2--{"jsonrpc":"2.0","params":{"value":{"kind":"begin","cancellable":false,"title":"loading","percentage":0},"token":2},"method":"$/progress"}
2020-03-11 10:37:32.14082864 [ThreadId 5] - <--2--{"jsonrpc":"2.0","params":{"value":{"kind":"report","percentage":0.5,"message":"Bar"},"token":2},"method":"$/progress"}
2020-03-11 10:37:32.140901552 [ThreadId 5] - <--2--{"jsonrpc":"2.0","params":{"value":{"kind":"report","percentage":1,"message":"Foo"},"token":2},"method":"$/progress"}
2020-03-11 10:37:32.14095176 [ThreadId 5] - <--2--{"jsonrpc":"2.0","params":{"value":{"kind":"end"},"token":2},"method":"$/progress"}
```

**Comment by expipiplus1** [comment] 2020-03-11 03:02
Oh, Removing all the notification code from the hie extension has no effect. The progress messages are displayed regardless?!

I guess this is good, although I'm a little unsure why now.

**Comment by expipiplus1** [comment] 2020-03-16 03:25
Sometimes I end up with multiple "⣆ loading" spinners on the status bar, I've not investigated yet to see if this is a coc.nvim issue or a language server issue. I haven't experienced this in vscode with the same language server though.

Would an unterminated workDoneProgress message cause this?

**Comment by chemzqm** [comment] 2020-03-16 04:14
> Sometimes I end up with multiple "⣆ loading" spinners on the status bar

What extensions are you using?
Use `:CocList extensions` to get all activated extensions.

**Comment by expipiplus1** [comment] 2020-03-16 05:28
I'm using just myport of vscode-hie-server for coc https://github.com/expipiplus1/vscode-hie-server

**Comment by fannheyward** [comment] 2020-03-16 07:09
What's `:CocList extensions` output?

**Comment by expipiplus1** [comment] 2020-03-16 07:59
Just `* vscode-hie-server [RTP] 0.0.37 /nix/store/yw807ns2vmjrv48avg74naqhr2zrxabr-vscode-hie-server`

I will try to get a log from HIE to see if it fails to send a `WorkDoneProgressEnd` message.

**Comment by masaeedu** [comment] 2020-04-04 05:03
I also occasionally see the multiple loading spinners that @expipiplus1 is describing. See: https://asciinema.org/a/2sIoKZ3YUwTDRHO71qbzbfgo8

**Comment by chemzqm** [comment] 2020-04-04 08:05
It's expected unless we can use floating windows for each progress to make it looks better
