### ISSUE TITLE
Vim crashes after the autocomplete window pops up and moving the cursor to watch some doc

### ISSUE THREAD

**Issue by Cyperwu** [neoclide/coc.nvim#2813] opened 2021-01-12 07:24 UTC
## versions

vim version: NVIM v0.5.0-nightly
node version: v10.14.2
coc.nvim version: 0.0.80-fff2a86b16
coc.nvim directory: /Users/wujiajie/.vim/plugged/coc.nvim
term: xterm-256color
platform: darwin

## Log of coc.nvim

2021-01-12T14:59:00.467 INFO (pid:59821) [attach] - receive request: documentSymbols []
2021-01-12T14:59:00.470 WARN (pid:59821) [attach] - Plugin not ready when received "documentSymbols" []
2021-01-12T14:59:00.503 ERROR (pid:59821) [attach] - Request error: documentSymbols [] TypeError: Cannot read property 'getDocumentSymbols' of undefined
    at MP.addAction (/Users/wujiajie/.vim/plugged/coc.nvim/build/index.js:254:2385)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2021-01-12T14:59:00.576 INFO (pid:59821) [services] - registered service "diagnostic-languageserver"
2021-01-12T14:59:00.591 INFO (pid:59821) [services] - registered service "eslint"
2021-01-12T14:59:00.591 INFO (pid:59821) [services] - eslint langserver state change: stopped => starting
2021-01-12T14:59:00.625 INFO (pid:59821) [language-client-index] - eslint started with 59832
2021-01-12T14:59:00.747 INFO (pid:59821) [services] - eslint langserver state change: starting => running
2021-01-12T14:59:00.752 INFO (pid:59821) [services] - service eslint started
2021-01-12T14:59:00.775 INFO (pid:59821) [coc-java] - Using java from /Library/Java/JavaVirtualMachines/jdk-11.0.6.jdk/Contents/Home, version: 11
2021-01-12T14:59:00.901 INFO (pid:59821) [services] - registered service "tsserver"
2021-01-12T14:59:00.963 INFO (pid:59821) [coc-java] - JDT Language Server starting at /Users/wujiajie/Downloads/Payroll
2021-01-12T14:59:00.963 INFO (pid:59821) [services] - registered service "java"
2021-01-12T14:59:00.969 INFO (pid:59821) [plugin] - coc.nvim 0.0.80-fff2a86b16 initialized with node: v10.14.2 after 497ms
2021-01-12T14:59:00.971 INFO (pid:59821) [language-client-index] - Language server "java" started with 59842
2021-01-12T14:59:01.219 INFO (pid:59821) [services] - service tsserver started
2021-01-12T14:59:02.819 INFO (pid:59821) [attach] - receive notification: showInfo []

## Describe the bug

Edit a file and wait for the autocomplete suggestion window pop up, then chose an option with detailed description (followed with a tilde), and neovim crashes

## Reproduce the bug

my minimal vimrc

  ```vim
set nocompatible
set runtimepath^=~/.vim/plugged/coc.nvim
filetype plugin indent on
syntax on
set hidden
  ```

my coc extensions

  * coc-yank 1.1.11 ~/.config/coc/extensions/node_modules/coc-yank
  * coc-git 2.0.1 ~/.config/coc/extensions/node_modules/coc-git
  * coc-vimlsp 0.10.1 ~/.config/coc/extensions/node_modules/coc-vimlsp
  * coc-java 1.5.3 ~/.config/coc/extensions/node_modules/coc-java
  * coc-tsserver 1.5.8 ~/.config/coc/extensions/node_modules/coc-tsserver
  * coc-tabnine 1.2.2 ~/.config/coc/extensions/node_modules/coc-tabnine
  * coc-snippets 2.2.1 ~/.config/coc/extensions/node_modules/coc-snippets
  * coc-eslint 1.3.2 ~/.config/coc/extensions/node_modules/coc-eslint
  * coc-diagnostic 0.9.0 ~/.config/coc/extensions/node_modules/coc-diagnostic
  * coc-sh 0.6.0 ~/.config/coc/extensions/node_modules/coc-sh
  * coc-rls 1.1.6 ~/.config/coc/extensions/node_modules/coc-rls
  * coc-solargraph 1.1.8 ~/.config/coc/extensions/node_modules/coc-solargraph
  * coc-python 1.2.12 ~/.config/coc/extensions/node_modules/coc-python
  * coc-json 1.3.2 ~/.config/coc/extensions/node_modules/coc-json
  * coc-vetur 1.2.0 ~/.config/coc/extensions/node_modules/coc-vetur
  * coc-html 1.2.4 ~/.config/coc/extensions/node_modules/coc-html
  * coc-yaml 1.1.0 ~/.config/coc/extensions/node_modules/coc-yaml
  * coc-css 1.2.5 ~/.config/coc/extensions/node_modules/coc-css
  * coc-rust-analyzer 0.9.0 ~/.config/coc/extensions/node_modules/coc-rust-analyzer

## Screenshots (optional)

![capture](https://user-images.githubusercontent.com/16120231/104281255-31d32880-54e8-11eb-9934-670493ed7650.gif)

**Comment by chemzqm** [comment] 2021-01-12 07:59
Duplicate of #2670

**Closed by chemzqm** 2021-01-12 07:59 UTC
Labels: Can't reproduce
