### ISSUE TITLE
coc-clang can‘t  auto-complete C++

### ISSUE THREAD

**Issue by Happy-zyy** [neoclide/coc.nvim#1892] opened 2020-05-11 03:38 UTC
<img width="407" alt="图片" src="https://user-images.githubusercontent.com/25721721/81522042-b7ac3c00-937b-11ea-93a6-302c5f2d1d68.png">

C is ok
but C++  auto-complete  not work

please help~thx

why 'iostream' file not found？~

**Comment by fannheyward** [comment] 2020-05-11 03:42
What's `coc-clang`? Do you mean https://github.com/clangd/coc-clangd ?

**Comment by Happy-zyy** [comment] 2020-05-11 03:43
> What's `coc-clang`? Do you mean https://github.com/clangd/coc-clangd ?

yes~

**Comment by fannheyward** [comment] 2020-05-11 03:53
What's your clangd version? Can't reproduce with `coc-clangd` + clangd 10.

Close this, you can open issue on https://github.com/clangd/coc-clangd

**Closed by fannheyward** 2020-05-11 03:53 UTC

**Comment by Happy-zyy** [comment] 2020-05-11 04:20
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by eddyekofo94** [comment] 2021-01-01 16:49
@Happy-zyy I had the same error but try adding the following on your` .bashrc/.zshrc`:
`export CPLUS_INCLUDE_PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1`

**Comment by dwolrdcojp** [comment] 2021-03-28 15:26
> @Happy-zyy I had the same error but try adding the following on your` .bashrc/.zshrc`:
> `export CPLUS_INCLUDE_PATH=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1`

Thanks this fixed for me. 

This helped me with

[ccls 2] Error use of undeclared identifier 'std'
