### ISSUE TITLE
Preview snippets like regular completions

### ISSUE THREAD

**Issue by theonlygusti** [neoclide/coc.nvim#1536] opened 2020-02-10 05:10 UTC
I would like to use tab to trigger completions, as well as cycle through the suggestions.

I copy-pasted the README's

```vim
" Use tab for trigger completion with characters ahead and navigate.
" Use command ':verbose imap <tab>' to make sure tab is not mapped by other plugin.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
```

for that. It works well for `[A]` (around) completions.

I am using coc-tabnine. Most tabnine suggestions are snippets. Pressing tab doesn't work to cycle through or submit them, it only types the first part of the snippet (up to the first non-word character?)

How do I make it so that tab also "confirm selects" the tabnine snippets, without exiting the pum and closing the list of suggestions?

**Comment by chemzqm** [comment] 2020-02-10 06:20
Duplicate of https://github.com/neoclide/coc-tabnine/issues/35

**Closed by chemzqm** 2020-02-10 06:20 UTC
