### ISSUE TITLE
"g:coc_global_extensions" fails to install the "scoped package".

### ISSUE THREAD

**Issue by yaegassy** [neoclide/coc.nvim#3080] opened 2021-05-07 09:34 UTC
## Result from CocInfo

```
## versions

vim version: NVIM v0.5.0-dev+1302-g8a93d1028
node version: v14.16.0
coc.nvim version: 0.0.80-012f0a9c23
coc.nvim directory: /Users/yaegassy/.local/share/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin
```

## Describe the bug

I've created several "scoped package" extensions.

I usually use `:CocInstall` to perform the installation, but when I try it with the `g:coc_global_extensions` setting, the installation fails.

**Setting(g:coc_global_extensions)**:

```
let g:coc_global_extensions = [
      \ '@yaegassy/coc-intelephense',
      \ '@yaegassy/coc-nginx'
      \ ]
```

**Error**

```
Install finished

- ✗  Cannot read property 'latest' of undefined
```

**Comment by fannheyward** [comment] 2021-05-08 01:41
Caused by https://github.com/neoclide/coc.nvim/issues/2173

**Comment by chemzqm** [comment] 2021-05-08 02:34
Fixed on latest release branch of coc.nvim.

**Closed by chemzqm** 2021-05-08 02:34 UTC
Labels: bug

**Comment by yaegassy** [comment] 2021-05-08 02:45
Thanks, @chemzqm @fannheyward 🙇

I have confirmed that it was installed correctly in my environment.
