### ISSUE TITLE
Conflict with clipboard=unnamed

### ISSUE THREAD

**Issue by mortyccp** [neoclide/coc.nvim#1136] opened 2019-09-01 03:05 UTC
## versions

vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 22 2019 04:01:19)
node version: v12.8.0
coc.nvim version: 0.0.74-c97d41aa1e
term: iTerm.app
platform: darwin
## Describe the bug
With .vimrc which has `set clipboard=unnamed`.
Execute `CocInfo` or `CocList` command would mess up the clipboard.

## Reproduce the bug

**Note**, if you can't provide minimal vimrc that could reproduce the issue,
it's most likely we can't do anything to help.

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  set clipboard=unnamed
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.

**Comment by oblitum** [comment] 2019-09-01 03:09
I can't reproduce this, must be another thing to blame.

**Comment by mortyccp** [comment] 2019-09-01 03:13
> I can't reproduce this, must be another thing to blame.

Are you using mac?

**Comment by oblitum** [comment] 2019-09-01 03:15
No. I didn't expect it could be macOS specific.

**Comment by oblitum** [comment] 2019-09-01 03:16
You should fill an actual `mini.vim` that reproduces the issue. You didn't do that, just copied the template.

**Comment by mortyccp** [comment] 2019-09-01 15:07
Updated the `mini.vim`

**Comment by chemzqm** [comment] 2019-09-10 04:45
It was fixed on latest release branch.

**Closed by chemzqm** 2019-09-10 04:45 UTC
