### ISSUE TITLE
arduino-language server gets stuck on "initializing languageserver.arduino"

### ISSUE THREAD

**Issue by drank40** [neoclide/coc.nvim#3594] opened 2022-01-22 18:52 UTC
## Info :

vim version: NVIM v0.6.1
node version: v17.3.0
coc.nvim version: 0.0.80-472fd14967
coc.nvim directory: /home/renny/.vim/plugged/coc.nvim
term: rxvt-unicode-256color
platform: linux

## Log of coc.nvim

2022-01-22T19:33:10.375 INFO (pid:73015) [services] - registered service "languageserver.arduino"
2022-01-22T19:33:10.378 INFO (pid:73015) [services] - arduino state change: stopped => starting
2022-01-22T19:33:10.766 INFO (pid:73015) [plugin] - coc.nvim initialized with node: v17.3.0 after 432ms
2022-01-22T19:33:10.783 INFO (pid:73015) [language-client-index] - Language server "languageserver.arduino" started with 73034
2022-01-22T19:34:35.295 INFO (pid:73015) [attach] - receive notification: runCommand [ 'workspace.showOutput' ]
2022-01-22T19:34:39.294 WARN (pid:73015) [plugin] - Slow action "runCommand" cost 3998ms
2022-01-22T19:36:00.102 INFO (pid:73015) [attach] - receive notification: showInfo []

## Describe the bug

If i try to open any .ino file the language server always shows "initializing languageserver.arduino" and never actually starts working. This used to work, so there must have been some sort of change recently that introduced this bug.
Im interfacing the language server with the default coc-settings.json suggested by the documentation. 

## Reproduce the bug

This a log provided by coc, and it seems as if the language server panics regardless of the command sent.

[log.txt](https://github.com/neoclide/coc.nvim/files/7919051/log.txt)

## A minimal nvimrc

[mini.vim.txt](https://github.com/neoclide/coc.nvim/files/7919056/mini.vim.txt)

**Comment by chemzqm** [comment] 2022-01-22 19:02
Need check output channel https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by drank40** [comment] 2022-01-22 19:04
I did come across that page, tho i do not exactly understand where the log of the language server is outputted. this is my current coc-settings.json

{
"languageserver":{
        "arduino":{ 
            "command":"/bin/arduino-language-server",
            "trace.server": "verbose",
            "initializationOptions": {
                "cacheDirectory": "/tmp/ardu"
            },
            "rootPatterns":["*.ino"],
            "filetypes":["arduino"],
            "args":["-cli", "/bin/arduino-cli", "-clangd", "/bin/clangd", "-cli-config", "/home/renny/.arduino15/arduino-cli.yaml", "-fqbn", "esp8266:esp8266:generic", "-log", "/home/renny/ardu.log"]
        }
    }
}

**Comment by listout** [comment] 2022-02-03 17:57
Don't why it's marked as 'Can't Reproduce', I'm facing the same issue. It's showing `[starting]` in `CocList services`

**Comment by chemzqm** [comment] 2022-02-03 18:09
The server doesn't send any response.

**Comment by chemzqm** [comment] 2022-02-20 14:32
Language server issue.

**Closed by chemzqm** 2022-02-20 14:32 UTC
