### ISSUE TITLE
Completion behaves strangely after lastest commit

### ISSUE THREAD

**Issue by wrvsrx** [neoclide/coc.nvim#2722] opened 2020-12-17 03:56 UTC
## Result from CocInfo

vim version: NVIM v0.5.0-dev+945-gc3b9c3587
node version: v15.4.0
coc.nvim version: 0.0.79-0d65fc2d9b
coc.nvim directory: /home/mars/.vim/plugged/coc.nvim
term: xterm-256color
platform: linux

## Describe the bug

After lastest commit of coc.nvim, coc inserts character when type \<backspace\>. It happens when there's word in the next line.

## Reproduce the bug

1. use minimal vimrc
2. install coc-texlab and open test.tex
2. input like following
```
\documentclass{article}

\begin{document}
[cursor]
\end{document}
```
3. at the cursor, input "\be", and input \<backspace\>，then it changes to "\bn" rather than "\b"
4. check out to 365c63e12f82675dfe3ec485a57eb4af964e421d (the previous commit)，it disappears.

Remark: it seems related to the next line, here's the gif (when the completion window closes, it means I input \<backspace\>. 
![1](https://user-images.githubusercontent.com/42770726/102441997-5a3d4380-405e-11eb-9b29-144ed9932779.gif)

Besides, it can be reproduced on coc-clangd either.

**Comment by chemzqm** [comment] 2020-12-17 04:44
Caused by `coc#_cancel` which could have side effect with `coc#_hide`.

**Comment by chemzqm** [comment] 2020-12-17 07:07
Fixed on latest release branch of coc.nvim.

**Closed by chemzqm** 2020-12-17 07:07 UTC
