### ISSUE TITLE
can't autofresh the complete item after backspace

### ISSUE THREAD

**Issue by chenjie199234** [neoclide/coc.nvim#1616] opened 2020-03-05 08:52 UTC
first i get this
it works fine
![normal](https://user-images.githubusercontent.com/29348971/75964097-948b8900-5f01-11ea-83c9-9cc95e839ac1.png)
then i input backspace
i get this,it doesn't refresh
![error](https://user-images.githubusercontent.com/29348971/75964183-b97ffc00-5f01-11ea-862f-702ec8fa3c73.png)

**Comment by chemzqm** [comment] 2020-03-05 09:17
Try minimal vimrc.

**Comment by chenjie199234** [comment] 2020-03-05 10:16
@chemzqm minimal vimrc still doesn't work
windows 10 1909
neovim-qt
0.4.3
init.vim:
![init](https://user-images.githubusercontent.com/29348971/75971760-2f3d9500-5f0d-11ea-8a0b-a000a269fb9a.png)
coc-setting:
![coc-setting](https://user-images.githubusercontent.com/29348971/75971779-35337600-5f0d-11ea-96f6-d4e1eec2eb56.png)
start at this:
![fine](https://user-images.githubusercontent.com/29348971/75971848-51371780-5f0d-11ea-831c-bcc67b1829d7.png)
input backspace:
![backspace](https://user-images.githubusercontent.com/29348971/75971877-5dbb7000-5f0d-11ea-85a8-0a84bf0669c8.png)

**Comment by fannheyward** [comment] 2020-03-06 10:53
This error is first caused by 78bdcf680ddad9ca685acd7e5b760e7fb080bb54, and fixed in https://github.com/neoclide/coc.nvim/commit/70dbceab2e0b281bcb68964d7a029ab15e3ac76f

**Comment by fannheyward** [comment] 2020-03-06 11:00
Works with TS, but still reproduce with gopls.

**Comment by chenjie199234** [comment] 2020-03-06 13:26
@fannheyward @chemzqm 
also happeneds on clangd for c/c++
start at this:
![2020-03-06-21:27:07](https://user-images.githubusercontent.com/29348971/76087358-f8d94600-5ff0-11ea-97da-3e9b76807991.png)
input backspace:
![2020-03-06-21:27:16](https://user-images.githubusercontent.com/29348971/76087431-13132400-5ff1-11ea-9a07-95ed06190eed.png)

**Comment by chenjie199234** [comment] 2020-03-06 13:28
@chemzqm @fannheyward 
i think this only works on javascript

**Comment by chemzqm** [comment] 2020-03-06 14:59
It's expected, since the server return in complete response on you type, and we can't do filter on backspace then.

**Closed by chemzqm** 2020-03-06 14:59 UTC

**Comment by chenjie199234** [comment] 2020-03-06 18:23
this is expected?
deoplete,ale,vim-lsp,ncm2,none of them works like this

**Comment by chemzqm** [comment] 2020-03-09 02:03
Yes, because we can't do filter and it's good idea to trigger completion on that case, manual trigger completion if you want to.

**Comment by hungpham3112** [comment] 2022-04-21 08:25
I have the same problem with this function in coc.nvim. Need to recreate this feature again. Today, when I work with python and julia, I see the same issue. Reopen?

**Comment by chemzqm** [comment] 2022-04-21 10:14
Refresh completion on backspace is not supported any more, because we can't distinguish backspace and completion cancelled by `<C-e>`

**Comment by jeroen-dhollander** [comment] 2022-07-22 09:05
Is there a way to reenable this, maybe through a keymapping that I would define?

I tried `inoremap <expr><bs> '<bs>' . coc#refresh()` but that doesn't seem to work :/

**Comment by chemzqm** [comment] 2022-07-27 18:57
No, you can use `"\<c-r>=coc#start()\<CR>"` for expr key-mapping.

**Comment by amgodoi** [comment] 2022-08-02 03:03
I tried:

"inoremap <silent><expr> <backspace> coc#pum#visible() ? "\<bs>\<CR>\<c-r>=coc#start()\<CR>" : "\<bs>"
and
"inoremap <silent><expr> <backspace> coc#pum#visible() ? "\<bs>\<CR>\<c-r>=coc#refresh()\<CR>" : "\<bs>"

both did not work. Any idea?

**Comment by chemzqm** [comment] 2022-08-02 14:07
I've made a fix, and you should use
```
    inoremap <silent><expr> <backspace> coc#pum#visible() ? "\<bs>\<c-r>=coc#start()\<CR>" : "\<bs>"
```

**Comment by amgodoi** [comment] 2022-08-02 15:15
Hi!

Worked with "coc#refresh" and "coc#start". More or less it worked.

But, backspace cannot refresh in some cases. When something is matched in a sparse way "coc#refresh"/"coc#start" cannot match anything. I do not know ... maybe a Language Server problem.

![image](https://user-images.githubusercontent.com/78377022/182409598-aa2dfc11-2651-4edf-95e7-bfc9d427cce4.png)

![image](https://user-images.githubusercontent.com/78377022/182409766-c144234f-9ff6-4b33-9d6e-8ff9736aea3b.png)

**Comment by chemzqm** [comment] 2022-08-02 15:23
Yes, the Language Server does strict match for trigger input.
