### ISSUE TITLE
Support BSD-look utility for english-like word completion

### ISSUE THREAD

**Issue by krishnakumarg1984** [neoclide/coc.nvim#1689] opened 2020-03-26 15:07 UTC
### Background
While the Google 10k words source provided by coc.nvim is good, when I write really long fiction/technical/editorial works in LaTeX and/or Markdown, these commonly-used words quickly become insufficient. I am then forced to manually type out the full (potentially) long words. 

### Use BSD-look
The [`look`](https://man.openbsd.org/look) utility is pre-installed on macOS, *BSD and pretty much every linux distribution (either pre-installed or available in repos), and since it is standard C-code, it can be even compiled for Windows natively (a cygwin package is already available anyway).   With its stdin/stdout interface and a host of other simple programmable interfaces, it can serve as a fantastic  English language completion utility. It uses the local dictionary installed in the OS, eg. in `/usr/share/dict/words` and allows for adding custom words to the dictionary (which may be useful for highly specialised technical/medical writing for example).

### Alternatives Considered
Before coc.nvim, I was using deoplete and then ncm-2. They both have implemented `look` completion sources, which I was quite happy with.
* [deoplete (neco-look)](https://github.com/ujihisa/neco-look)
* [ncm2-look.vim](https://github.com/filipekiss/ncm2-look.vim)

### Additional context
Please retain google 10k source with a lower completion priority than `look`.

**Comment by oblitum** [comment] 2020-03-26 20:18
Doesn't [coc-sources](https://github.com/neoclide/coc-sources), which provides coc-dictionary, cover this?

**Comment by krishnakumarg1984** [comment] 2020-03-26 20:46
@oblitum I don't think so, but I could be wrong. `coc-words` uses Google10k. I didn't have a good experience with using `coc-dictionary`.  Should I be opening up this issue report/feature request in that github repo instead of here?

**Comment by oblitum** [comment] 2020-03-26 21:10
> Should I be opening up this issue report/feature request in that github repo instead of here?

No idea, but quite possible, as coc.nvim is generic and shouldn't provide any specific source builtin.

**Comment by chemzqm** [comment] 2020-03-27 03:32
Duplicate of https://github.com/neoclide/coc-sources/issues/24.
You can create completion source yourself to best fit your need.

**Closed by chemzqm** 2020-03-27 03:32 UTC
