### ISSUE TITLE
neovim gopls  stopped responding with latest commit.

### ISSUE THREAD

**Issue by ehrktia** [neoclide/coc.nvim#1891] opened 2020-05-10 20:12 UTC
gopls stopped working, not responding/updating from init state to running.It happens in latest commit.Older commit works with no issues.

## Result from CocInfo

**working commit - gopls**
```console

## versions

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 13 2020 07:47:09)
node version: v13.11.0
coc.nvim version: 0.0.78-030aef2f6d
term: iTerm.app
platform: darwin

## Output channel: snippets

[Info 19:36:36] Using ultisnips directories: UltiSnips /Users/karthickayyapillai/.config/coc/ultisnips
[Info 19:36:36] Using ultisnips python command: pyx

````
**latest commit -gopls stopped responding**
```console
## versions

vim version: NVIM v0.4.3
node version: v13.11.0
coc.nvim version: 0.0.78-fd9e7d3972
term: iTerm.app
platform: darwin

## Output channel: snippets

[Info 19:42:42] Using ultisnips directories: UltiSnips /Users/karthickayyapillai/.config/coc/ultisnips
[Info 19:42:42] Using ultisnips python command: pyx

````
## Describe the bug
gopls language server used for go completion is stuck at init state.`:CocConfig` output below.
```console
{
  "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod"],
      "disableWorkspaceFolders": true,
      "filetypes": ["go"]
    }
  }
}
````

As mentioned above when using 0.0.78-fd9e7d3972 commit in master branch the gopls stopped responding and it stays in init state when inspected with `:CocList` `services` does not start to running state.
Due to language server not responding , the goimports does not work neither it provides an option to add the imports to go file.

## Reproduce the bug
Tried with nvim & vim both to check the issue.
 gopls using command line version works as expected.
```console
golang.org/x/tools/gopls 0.4.0
    golang.org/x/tools/gopls@v0.4.0 h1:G4+YP9kaV4dJb79J5MobyApxX493Qa6VoiTceUmxqik=
````

Version and commit of coc-nvim used are provided in cocinfo above.
**min vimrc**
```
call plug#begin('~/.config/nvim/plugged')
"list of plugins used"
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
let g:coc_snippet_next = '<tab>'
" Mappings using CoCList:
" Show all diagnostics.
nnoremap <silent> <space>a  :<C-u>CocList diagnostics<cr>
" Manage extensions.
nnoremap <silent> <space>e  :<C-u>CocList extensions<cr>
" Show commands.
nnoremap <silent> <space>c  :<C-u>CocList commands<cr>
" Find symbol of current document.
nnoremap <silent> <space>o  :<C-u>CocList outline<cr>
" Search workspace symbols.
nnoremap <silent> <space>s  :<C-u>CocList -I symbols<cr>
" Do default action for next item.
nnoremap <silent> <space>j  :<C-u>CocNext<CR>
" Do default action for previous item.
nnoremap <silent> <space>k  :<C-u>CocPrev<CR>
" Resume latest coc list.
nnoremap <silent> <space>p  :<C-u>CocListResume<CR>
inoremap <silent><expr> <TAB>
            \ pumvisible() ? "\<C-n>" :
            \ <SID>check_back_space() ? "\<TAB>" :
            \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~# '\s'
endfunction
"make tab to expand snippets"
inoremap <silent><expr> <TAB>
            \ pumvisible() ? coc#_select_confirm() :
            \ coc#expandableOrJumpable() ? "\<C-r>=coc#rpc#request('doKeymap', ['snippets-expand-jump',''])\<CR>" :
            \ <SID>check_back_space() ? "\<TAB>" :
            \ coc#refresh()

function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~# '\s'
endfunction
" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>
function! s:show_documentation()
  if (index(['nvim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
```
**General OS details**
Tried in osx and linux.
- OSX
- LInux
Please let me know if you require more details.

**Comment by chemzqm** [comment] 2020-05-10 20:38
Duplicate of #1878

**Closed by chemzqm** 2020-05-10 20:38 UTC
