### ISSUE TITLE
Support semantic tokens

### ISSUE THREAD

**Issue by heftig** [neoclide/coc.nvim#2053] opened 2020-06-09 12:34 UTC
It would be nice if CoC would retrieve semantic tokens from the LS in order to enable semantic highlighting. The `rust-analyzer` LS has support for this.

**Comment by oblitum** [comment] 2020-06-10 23:07
Duplicate of #1671.

https://github.com/neoclide/coc.nvim/issues/1671#issuecomment-616895670

**Comment by oblitum** [comment] 2021-06-15 14:35
Done. See #2756 and #3048.

**Closed by oblitum** 2021-06-15 14:35 UTC
Labels: enhancement
