### ISSUE TITLE
Provide a way to let color theme plugin override the highlight of the "brackets" in floating window

### ISSUE THREAD

**Issue by crusoexia** [neoclide/coc.nvim#1248] opened 2019-10-08 03:32 UTC
Tried a white but cannot find a way to override the highlight of brackets in the floating window:

![Screen Shot 2019-10-08 at 11 21 55 AM](https://user-images.githubusercontent.com/5928754/66365315-2036d300-e9bf-11e9-9475-f897bb1f7443.png)

expectation:

want a way to let other plugins override it.

**Comment by chemzqm** [comment] 2019-10-08 03:35
The highlight should be added by your other plugin, can't help.

**Comment by crusoexia** [comment] 2019-10-08 04:26
@chemzqm which highlight group should I use? Tried a few in [coc doc](https://github.com/neoclide/coc.nvim/blob/master/doc/coc.txt) but none of them works.

**Comment by crusoexia** [comment] 2019-10-08 04:29
build-in `Normal` group can affect it, but absolutely I don't want to change `Normal` highlight for it.

**Comment by chemzqm** [comment] 2019-10-08 05:03
The highlight is added with background neovim with syntax plugins loaded only.

**Comment by ckipp01** [comment] 2019-12-22 15:45
@crusoexia did you ever find a fix for this? I still have issues with this with pretty much every theme I try.

**Comment by crusoexia** [comment] 2019-12-27 07:00
@ckipp01 no, I just choose the themes which let the issue not that obvious.

**Comment by ckipp01** [comment] 2019-12-27 09:41
@crusoexia ah, I a was hoping you found a fix. I ended up just setting `"coc.preferences.enableFloatHighlight": false` to get rid of all highlighting in the floating window.

**Comment by joshdick** [comment] 2020-01-15 15:05
I know this issue is closed now, but FWIW:

Per https://github.com/joshdick/onedark.vim/issues/197#issuecomment-574422967, this appears to be caused by coc using the background color from the `Normal` highlight group when drawing those characters in the floating window. A fix would be for coc to not to set/override a background color in this case.

**Comment by ckipp01** [comment] 2020-01-15 16:27
@chemzqm or @fannheyward, do you think it's a possibility to make this change? I've seen this issue pop up in a few different issues, and I know I'd love to not have to have special code in my vim config just to account for this.

**Comment by jupblb** [comment] 2020-02-07 13:37
Had the same issue when using `gruvbox` colorscheme. Wouldn't work even if `init.vim` contained only coc.nvim configuration from readme + `colorscheme gruvbox`. It does work either with @ckipp01 solution (thank you so much for that!) or when setting the colorscheme manually after opening the editor (requires `:syntax on` too in order to produce desired effect).

**Comment by oblitum** [comment] 2020-02-07 13:54
Even though this indeed looks like an issue, have you tried setting the highlight of the floating window background to match that of the char? On help you can find highlight group for the floating window, I had to use it myself to get it nice.

**Comment by jupblb** [comment] 2020-02-07 16:44
I don't exactly know how to do that. Played a bit with setting `Pmenu` and `PmenuSel` but it wouldn't change the color of those parts of the floating window.

**Comment by oblitum** [comment] 2020-02-07 16:47
Read docs/play with `:h CocFloating@en`, `:h CocErrorFloat@en`, etc.

**Comment by jupblb** [comment] 2020-02-07 17:35
Tried different combinations and it seems that this background colouring is independent of `CocFloating`, `CocErrorFloat`, ... :/ (Also I can see that `CocFloating` is linked to `Pmenu` by default.) Thanks for the suggestion though!

**Comment by oblitum** [comment] 2020-02-07 17:41
@jupblb I know it is, reason why I state that can be used to match the background with the background of this strange char you have no control over. Or you can simply patch the colorscheme you're using. I think coc.nvim should not provide special highlighting options for characters, this is an issue specific of a colorscheme, if you think a highlight group is broken with it, you can simply get the highlight group that gets broken, and override it for correction.

**Comment by joshdick** [comment] 2020-02-07 18:08
> I think coc.nvim should not provide special highlighting options for characters, this is an issue specific of a colorscheme, if you think a highlight group is broken with it, you can simply get the highlight group that gets broken, and override it for correction.

Like I said [above](https://github.com/neoclide/coc.nvim/issues/1248#issuecomment-574700784), this happens because coc uses the background color from the `Normal` highlight group when drawing those characters in the floating window.

Many colorschemes are likely to set an explicit background color for this highlight group, so I wouldn't classify this problem as being caused by specific colorschemes.

**Comment by chemzqm** [comment] 2020-02-14 15:50
I've made Normal group linked to CocFloating.

**Comment by chemzqm** [comment] 2020-02-14 15:55
The only way for now is overwrite related highlight group in your vimrc.

**Comment by ungrim97** [comment] 2020-02-17 14:01
@chemzqm Can I make an appeal for this to be looked at.

The issue as far as I see is that the '()' and maybe others do not use the same set of highlighting as the rest of the floating pane.

Instead they use the Normal highlight group. As such it is impossible to make the float all match unless the whole float matches the current main background colour.

I have no reall desire for there to be a specific group for these characters. Only that the same group is used for those characters as the surrounding ones

**Comment by ungrim97** [comment] 2020-02-17 14:04
The rest of the float uses the CocFloating guibg colour. for some reason the `()` don't and instead use the Normal guibg colour

**Comment by chemzqm** [comment] 2020-02-18 02:15
@ungrim97 we don't have an api to check the background color of specific highlight group, you should be able to overwrite highlight group of pairs in your vimrc.

**Comment by joshdick** [comment] 2020-02-18 02:54
@chemzqm What @ungrim97 is asking is, why are the problem characters in the float not rendered with the same `CocFloating` highlight group inside the float, that most other characters inside floats seem to use with no problems?

**Comment by chemzqm** [comment] 2020-02-18 03:27
@joshdick it should be using Normal for guibg, not like others.

**Comment by chemzqm** [comment] 2020-02-27 04:41
https://github.com/neoclide/coc.nvim/wiki/F.A.Q#highlight-of-background-seems-wrong-with-floating-window

**Closed by chemzqm** 2020-02-27 04:41 UTC

**Comment by gvolpe** [comment] 2020-04-05 13:28
Hi @chemzqm ,

Does that workaround only work for the `onedark` theme? I'm using the [tender](https://github.com/jacoborus/tender.vim) theme and can confirm this doesn't work on NeoVim 0.4.3.

**Comment by chemzqm** [comment] 2020-04-05 21:28
You checkout the highlight group yourself

**Comment by gvolpe** [comment] 2020-04-06 07:50
I did but unfortunately I couldn't figure it out :disappointed: I'll raise an issue in the theme repo and see if I can get any help there.
