### ISSUE TITLE
what is the difference between activate\deactivate and enable\disable ?

### ISSUE THREAD

**Issue by 4volodin** [neoclide/coc.nvim#1644] opened 2020-03-10 20:44 UTC
Who knows, what is the difference between activate\deactivate and enable\disable states of extensions ?

**Comment by chemzqm** [comment] 2020-03-11 01:35
Duplicate of https://github.com/neoclide/coc.nvim/issues/1503

**Closed by chemzqm** 2020-03-11 01:35 UTC
