### ISSUE TITLE
Suggest both lowercase and uppercase candidates?

### ISSUE THREAD

**Issue by 097115** [neoclide/coc.nvim#1630] opened 2020-03-07 04:44 UTC
Is it possible to make CoC suggestions case insensitive? Like, I type `f` and it suggests me both `foo` and `Foobar`? How do I do it?

**Comment by oblitum** [comment] 2020-03-07 04:50
It works already, just ranked/ordered differently depending on what you type and case you use, but both are displayed regardless of case.

**Comment by for-coursera** [comment] 2020-03-07 04:59
@oblitum 

No, it doesn't:

![lower](https://i.imgur.com/2D4vBZ1.png)
![upper](https://i.imgur.com/FTgyP2P.png)

So, would be great if you could re-open the issue.

**Comment by oblitum** [comment] 2020-03-07 05:16
@for-coursera

> Like, I type f and it suggests me both foo and Foobar?

![02:13:29_07-03-2020](https://user-images.githubusercontent.com/1269815/76137269-a2343200-6019-11ea-9c59-72345b712498.png)

**Comment by 097115** [comment] 2020-03-07 05:21
@oblitum 

And still, I second @for-coursera, it DOES NOT shows both lower and upper case suggestion even with the basic buffer words completion (and just inn case, Vim's `ignorecase` is set). So, PLEASE, re-open the issue.

**Comment by oblitum** [comment] 2020-03-07 05:29
I have put a screeshot proving it worked just like I stated. If you want a problem reproduced, please fill the issue template and be more specific on your request.

**Comment by chemzqm** [comment] 2020-03-07 07:10
We did exact match of the first letter for specific sources to provide better results.
There are configurations to disable this feature.

@oblitum  If we need more Info, just label it. We should not close the issue.

**Comment by chemzqm** [comment] 2020-03-09 02:38
Use 
```
"coc.source.around.firstMatch": false,
"coc.source.buffer.firstMatch": false
```
in your coc-settings.json to disable first letter strict match.

**Closed by chemzqm** 2020-03-09 02:38 UTC
Labels: needs more info, question

**Comment by nullromo** [comment] 2020-12-03 23:40
I have a similar issue, but it extends beyond just the first letter of the match. For example, if I start typing in "`VI`," it will not suggest things starting with "`vi`" or "`Vi`". See attached screenshot.
![Capture](https://user-images.githubusercontent.com/8991581/101102651-d7a48680-357d-11eb-8411-738605b8379c.PNG)

**Comment by chemzqm** [comment] 2020-12-04 03:02
It's expected, since it use smartcase.

**Comment by nullromo** [comment] 2020-12-04 18:44
Ok, so it does not take into account the setting of the global `smartcase` variable? Because `set nosmartcase` did not change the behavior. That's fine; thanks for explaining.
