### ISSUE TITLE
Coc always goes to coc directory after update and not going back

### ISSUE THREAD

**Issue by sandangel** [neoclide/coc.nvim#198] opened 2018-11-27 23:15 UTC
**Describe the bug**
When I run PlugUpdate, coc always goes to coc directory in vim plugin

**To Reproduce**
when a new Coc update release, run PlugUpdate
the current working directory changes to coc plugin directory and affects the FZF search.

**Expected behavior**

it should go back to the current working directory

**Screenshots**

**Desktop (please complete the following information):**
 - Terminal: [e.g. iTerm2]
 - Version: [e.g. v3.1.0]

**Additional context**

**Comment by chemzqm** [comment] 2018-11-27 23:21
Could be other plugin cause this problem, you can try `:call coc#util#install()` and then `echo getcwd()`.
Coc only change cwd for the terminal buffer, so unless you use command in that terminal buffer, your cwd should be keep unchanged.

**Comment by sandangel** [comment] 2018-11-27 23:30
yeah I think fzf is using terminal buffer. so coc change the terminal buffer directory will affect fzf.

**Comment by chemzqm** [comment] 2018-11-27 23:39
I can't reproduce your problem, did you trigger fzf in that terminal buffer?

**Comment by chemzqm** [comment] 2018-11-27 23:39
Checkout result of `:echo getcwd()` before trigger fzf.

**Comment by sandangel** [comment] 2018-11-28 00:36
I’m using build from source approach for update. this is not always, but happen sometimes. Maybe try update while fzf is open cause the problem. I will try to find the best way to reproduce and report it later

**Comment by chemzqm** [comment] 2018-11-28 00:41
If you use `{'do': 'yarn install'}` for update, the cwd is handled by vim-plug, it should swtich your cwd back after update.

**Comment by chemzqm** [comment] 2018-11-28 17:20
Closing, since it's not problem of coc.

**Closed by chemzqm** 2018-11-28 17:20 UTC
Labels: question
