### ISSUE TITLE
NeoVim statusline showing wrong Python version

### ISSUE THREAD

**Issue by rollschild** [neoclide/coc.nvim#1455] opened 2020-01-08 19:48 UTC
I used to have Python `3.8-dev` installed via `pyenv` but I deleted it and now I only have `3.7.5` and it's global default.
![Screenshot 2020-01-08 12 30 34](https://user-images.githubusercontent.com/6456628/72010340-49b10600-321d-11ea-8bf3-732bbceed5cc.png)

But now when I use NeoVim to open a python file the statusline still shows me `Python 3.8.1 64-bit` even though I don't have that anymore on this machine. Can anybody please help me with this?
![Screenshot 2020-01-08 12 34 32](https://user-images.githubusercontent.com/6456628/72010452-7bc26800-321d-11ea-89a4-06d46f424e68.png)

NeoVim 0.4.3

**Comment by oblitum** [comment] 2020-01-08 20:17
Must be a duplicate of https://github.com/neoclide/coc-python/issues/55. If it's a coc-python specific issue, you should post it on that repo.

**Comment by rollschild** [comment] 2020-01-08 20:19
@oblitum That issues looks a bit long. I will spend some time reading through and if it's indeed an duplicate I will close this one. Thank you for the help.

**Closed** 2020-01-08 20:23 UTC
