### ISSUE TITLE
CocRestart fails

### ISSUE THREAD

**Issue by laoshaw** [neoclide/coc.nvim#4843] opened 2023-12-29 20:07 UTC
## versions

vim version: VIM - Vi IMproved 9.0 9000749
node version: v18.17.1
coc.nvim version: 0.0.82-d1568d56 2023-09-29 19:43:34 +0800
coc.nvim directory: /home/tester/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim
```
2023-12-29T14:02:11.403 INFO (pid:7888) [configurations] - Add folder configuration from cwd: /home/tester/devel///SDK/.vim/coc-settings.json
2023-12-29T14:02:11.649 WARN (pid:7888) [commands] - Command prettier.createConfigFile already registered
2023-12-29T14:02:11.649 WARN (pid:7888) [commands] - Command prettier.openOutput already registered
2023-12-29T14:02:11.649 WARN (pid:7888) [commands] - Command prettier.forceFormatDocument already registered
2023-12-29T14:02:11.649 WARN (pid:7888) [commands] - Command prettier.formatFile already registered
2023-12-29T14:02:11.689 INFO (pid:7888) [plugin] - coc.nvim initialized with node: v18.17.1 after 321
2023-12-29T14:02:11.701 INFO (pid:7888) [services] - LanguageClient clangd state change: stopped => starting
2023-12-29T14:02:11.707 INFO (pid:7888) [language-client-index] - Language server "clangd" started with 7900
2023-12-29T14:02:11.717 INFO (pid:7888) [services] - LanguageClient clangd state change: starting => running
2023-12-29T14:02:11.721 INFO (pid:7888) [services] - service clangd started
2023-12-29T14:02:11.739 INFO (pid:7888) [core-watchman] - watchman watching project: /home/tester/devel///SDK
2023-12-29T14:03:11.103 INFO (pid:7888) [attach] - receive notification: showInfo []                                           
 ```
## Describe the bug

:CocStart shows below

![image](https://github.com/neoclide/coc.nvim/assets/18351761/cbb39124-239b-4bde-93fb-4d64b012ebfe)

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  set runtimepath^=/path/to/coc.nvim
  filetype plugin indent on
  syntax on
  set hidden
  ```

- Start (neo)vim with command: `vim -u mini.vim`

- Operate vim.
same result:
![image](https://github.com/neoclide/coc.nvim/assets/18351761/0a563a11-d338-4936-9195-4d3ba6388356)

**Comment by fannheyward** [comment] 2024-01-03 03:11
https://github.com/neoclide/coc.nvim/pull/4850 fixed the `g:coc_status` issue.

The `abnormal exit` reproduced with vim, not nvim.

**Comment by cridemichel** [comment] 2024-01-19 15:24
the culprit of this error message is this function 
```
function! coc#client#stop(name) abort
  let client = get(s:clients, a:name, v:null)
  if empty(client) | return 1 | endif
  let running = coc#client#is_running(a:name)
  if !running
    echohl WarningMsg | echom 'client '.a:name. ' not running.' | echohl None
    return 1
  endif
  if s:is_vim
    call job_stop(ch_getjob(client['channel']), 'term')
  else
    call jobstop(client['chan_id'])
  endif
  sleep 200m

  if coc#client#is_running(a:name)
    echohl Error | echom 'client '.a:name. ' stop failed.' | echohl None
    return 0
  endif

  call s:on_exit(a:name, 0)
  echohl MoreMsg | echom 'client '.a:name.' stopped!' | echohl None
  return 1
endfunction
```
which can be found in "autoload/coc/client.vim"
The function "job_stop()" triggers the "exit_cb" handler associated to the job, which is 
set in function "s:start()", i.e.
```
 let options = {
          \ 'in_mode': 'json',
          \ 'out_mode': 'json',
          \ 'err_mode': 'nl',
          \ 'err_cb': {channel, message -> s:on_stderr(self.name, split(message, "\n"))},
          \ 'exit_cb': {channel, code -> s:on_exit(self.name, code)},
          \ 'env': {
            \ 'NODE_NO_WARNINGS': '1',
            \ 'VIM_NODE_RPC': '1',
            \ 'TMPDIR': tmpdir,
          \ }
          \}
```
According to vim manual (:h channel.txt) an handler can be defined also this way (i.e. without lambdas):
```
 let options = {
          \ 'in_mode': 'json',
          \ 'out_mode': 'json',
          \ 'err_mode': 'nl',
          \ 'err_cb':  function('s:on_stderr'), 
          \ 'exit_cb': function('s:on_exit'),
          \ 'env': {
            \ 'NODE_NO_WARNINGS': '1',
            \ 'VIM_NODE_RPC': '1',
            \ 'TMPDIR': tmpdir,
          \ }
          \}
```
and this change made the job in that  "s:on_exit" is correctly called with second argument (code) equal to 0.
If this fix is acceptable, I can also issue pull request,

best Cristiano

**Comment by cridemichel** [comment] 2024-01-19 17:40
> #4850 fixed the `g:coc_status` issue.
> 
> The `abnormal exit` reproduced with vim, couldn't with nvim.

Hi,
probabily with *neovim* the error message couldn't be reproduced since, according to its manual: 							
```
*on_exit*
Arguments passed to on_exit callback:
  0: |job-id|
  1: Exit-code of the process, or 128+SIGNUM if by signal (e.g. 143 on SIGTERM).
  2: Event type: "exit"
```
so that if exit code of the process is -1, 143 (SIGTERM) is passed as argumento of the on_exit callback,
since jobstop() send a SIGTERM signal.
Differently, *vim* passes to the "exit_cb" callback the exit code of the process, which is -1.
Maybe one should ignore a process exit code equal to -1, not issuing any error message?
 
my two cents
best C.

**Comment by cridemichel** [comment] 2024-01-23 07:22
Hi, 
I noticed that if channel connection are close before restarting the server, the abnormal exit does not occurr anymore. This means that if in the function "coc#rpc#restart()" which is in autoload/coc/rpc.vim, i.e.

```
function! coc#rpc#restart()
  if empty(s:client)
    call coc#rpc#start_server()
  else
    call coc#highlight#clear_all()
    call coc#ui#sign_unplace()
    call coc#float#close_all()
    autocmd! coc_dynamic_autocmd
    autocmd! coc_dynamic_content
    autocmd! coc_dynamic_option
    call coc#rpc#request('detach', [])
    unlet g:coc_status
    let g:coc_service_initialized = 0
    sleep 100m
    if exists('$COC_NVIM_REMOTE_ADDRESS')
      call coc#rpc#close_connection()
      sleep 100m
      call coc#rpc#start_server()
    else
      let s:client['command'] = coc#util#job_command()
      call coc#client#restart(s:name)
      call s:check_vim_enter()
    endif
    echohl MoreMsg | echom 'starting coc.nvim service' | echohl None
  endif
endfunction
```

we call  coc#rpc#close_connection() just before  call coc#client#restart(s:name), i.e. 
```
function! coc#rpc#restart()
  if empty(s:client)
    call coc#rpc#start_server()
  else
    call coc#highlight#clear_all()
    call coc#ui#sign_unplace()
    call coc#float#close_all()
    autocmd! coc_dynamic_autocmd
    autocmd! coc_dynamic_content
    autocmd! coc_dynamic_option
    call coc#rpc#request('detach', [])
    unlet g:coc_status
    let g:coc_service_initialized = 0
    sleep 100m
    if exists('$COC_NVIM_REMOTE_ADDRESS')
      call coc#rpc#close_connection()
      sleep 100m
      call coc#rpc#start_server()
    else
      let s:client['command'] = coc#util#job_command()
      call coc#rpc#close_connection() # close connections before restarting
      sleep 100m
      call coc#client#restart(s:name)
      call s:check_vim_enter()
    endif
    echohl MoreMsg | echom 'starting coc.nvim service' | echohl None
  endif
endfunction
```
the abnormal exit does not occurr anymore. Is this safe?

best C.


 the abnormal exits does not occurr

**Comment by cridemichel** [comment] 2024-01-23 07:51
Hi,
I noticed that if server is stopped by closing channel connections, the abnormal exit does not occurr anymore.  In other words, consider the function "coc#rpc#restart()", which is in autoload/coc/rpc.vim, i.e.

function! coc#rpc#restart()
  if empty(s:client)
    call coc#rpc#start_server()
  else
    call coc#highlight#clear_all()
    call coc#ui#sign_unplace()
    call coc#float#close_all()
    autocmd! coc_dynamic_autocmd
    autocmd! coc_dynamic_content
    autocmd! coc_dynamic_option
    call coc#rpc#request('detach', [])
    unlet g:coc_status
    let g:coc_service_initialized = 0
    sleep 100m
    if exists('$COC_NVIM_REMOTE_ADDRESS')
      call coc#rpc#close_connection()
      sleep 100m
      call coc#rpc#start_server()
    else
      let s:client['command'] = coc#util#job_command()
      call coc#client#restart(s:name)
      call s:check_vim_enter()
    endif
    echohl MoreMsg | echom 'starting coc.nvim service' | echohl None
  endif
endfunction

if server is stoped by closing connections, i.e. the function is modified as follows:

function! coc#rpc#restart()
  if empty(s:client)
    call coc#rpc#start_server()
  else
    call coc#highlight#clear_all()
    call coc#ui#sign_unplace()
    call coc#float#close_all()
    autocmd! coc_dynamic_autocmd
    autocmd! coc_dynamic_content
    autocmd! coc_dynamic_option
    call coc#rpc#request('detach', [])
    unlet g:coc_status
    let g:coc_service_initialized = 0
    sleep 100m
    if 1 "exists('$COC_NVIM_REMOTE_ADDRESS') by doing this connections are closed and server started
      call coc#rpc#close_connection()
      sleep 100m
      call coc#rpc#start_server()
    else
      let s:client['command'] = coc#util#job_command()
      call coc#client#restart(s:name)
      call s:check_vim_enter()
    endif
    echohl MoreMsg | echom 'starting coc.nvim service' | echohl None
  endif
endfunction

the abnormal exit does not occurr anymore. I also noticed that COC_NVIM_REMOTE_ADDRESS variable is not set, 
maybe is this the real culprit of the abnormal exit? 
HTH 

best C.

**Comment by Lmills71** [comment] 2024-01-23 07:56
😊

**Closed** 2024-02-21 08:05 UTC
