### ISSUE TITLE
Insert mode space/character overlap triggering completion

### ISSUE THREAD

**Issue by Parasrah** [neoclide/coc.nvim#476] opened 2019-03-01 22:37 UTC
**Result from CocInfo**
Run `:CocInfo` command and paste the content below.

## versions

vim version: NVIM v0.3.1
node version: v8.9.0
coc.nvim version: 0.0.57
term: xterm-kitty
platform: linux

## Output channel: tsserver
[Info  - 14:47:22] Forking TSServer
PATH: $HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$HOME/.nvm/versions/node/v10.15.1/bin:$HOME/.cargo/bin:/$HOME/Tools/.bin/:$HOME/.cargo/bin:$HOME/.local/kitty.app/bin:$HOME/Tools/Java/JRE/bin:$HOME/Scripts/local:$HOME/Scripts/global:$HOME/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:$HOME/.config/nvim/pack/minpac/opt/fzf/bin 
[Info  - 14:47:22] Started TSServer
{
  "path": "$PROJECT/node_modules/typescript/lib",
  "_api": {
    "versionString": "3.2.2",
    "version": "3.2.2"
  }
}

_Note: I have replaced some sensitive paths in the output_

**Describe the bug**

I have noticed when typing in insert mode, when I am typing quickly sometimes the completion is triggered. It seems to happen when I press a character before I have fully let go of the space button. I haven't noticed this until recently (about the last couple weeks)

I have disabled all of my other settings and plugins and it's still occurring.

**To Reproduce**

1. Go to a file with lots of contents to trigger completion
2. Press a letter and space in quick succession, trying to change how quickly you press each and how much overlap there is between both

I personally found going to a file with many repeats of a word like "const" and testing "c" and \<space\> revealed best results. I would end up with a line like "c cc c c const c c c c" which shouldn't happen unless completion was triggered

**Screenshots**

**Comment by chemzqm** [comment] 2019-03-02 04:17
> I would end up with a line like "c cc c c const c c c c" which shouldn't happen unless completion was triggered

The `const` should only inserted when you have `<C-n>` or `<C-y>` triggered after pum visible, but I can't reproduct it by type `c` and `<space>`.

**Comment by Parasrah** [comment] 2019-03-02 06:15
All good I'll try to keep investigating on my end. If nobody else has reported it than either it's something specific to my environment or I have a bad habit while typing quickly that I need to rectify. In any case thanks for looking into it and feel free to close 👍

Btw also a huge thanks for providing this plugin, and for being so responsive. I think I speak for everyone when I say we really appreciate it and it makes a significant impact in our daily lives.

**Comment by chemzqm** [comment] 2019-03-05 06:02
It should be triggered by other plugin, closing.

**Comment by karismatic-megafauna** [comment] 2019-05-15 06:44
I am also experiencing something of the same... it seems to be related to when i do space as well...

Here is my best attempt at reproducing 
![coc_vim_issues](https://user-images.githubusercontent.com/1623740/57753955-3eafd100-76a2-11e9-9308-b7ca441b53fb.gif)

**Comment by karismatic-megafauna** [comment] 2019-05-15 16:03
I also have `universal ctags` installed but not really working, i will try removing all that stuff and see if I can still reproduce.

**Comment by chemzqm** [comment] 2019-05-25 15:33
It should be caused by sync vim sources, you vim will be blocked when triggering that none async vim completion source so it can't insert character you type.
My advice is avoid sync vim completion source, the tmux source have changed to use async job.

**Closed by chemzqm** 2019-05-25 15:33 UTC
Labels: Can't reproduce
