### ISSUE TITLE
gopls fails to start with UnhandledRejection: server not initialized

### ISSUE THREAD

**Issue by ronakg** [neoclide/coc.nvim#1622] opened 2020-03-05 20:25 UTC
## Result from CocInfo

```

## versions

vim version: NVIM v0.4.3
node version: v13.10.1
coc.nvim version: 0.0.75-ab29c13082
term: iTerm.app
platform: darwin

## Messages[coc.nvim] json: cannot unmarshal object into Go struct field PublishDiagnosticsClientCapabilities.capabilities.textDocument.publishDiagnostics.tagSupport of type bool
[coc.nvim] Server gopls failed to start: json: cannot unmarshal object into Go struct field PublishDiagnosticsClientCapabilities.capabilities.textDocument.publishDiagnostics.tagSupport of type bool
[coc.nvim] error: UnhandledRejection: server not initialized
Error: server not initialized
    at handleResponse (/Users/rogandhi/dotfiles/vim/plugged/coc.nvim/build/index.js:15873:48)
    at processMessageQueue (/Users/rogandhi/dotfiles/vim/plugged/coc.nvim/build/index.js:15700:17)
    at Immediate.<anonymous> (/Users/rogandhi/dotfiles/vim/plugged/coc.nvim/build/index.js:15684:13)
    at processImmediate (internal/timers.js:456:21)
47 lines yanked

## Output channel: explorer


## Output channel: git
Looking for git in: git
> git rev-parse --show-toplevel
resolved root: /Users/rogandhi/work/go/src/github.com/fatih/motion
resolved root: /Users/rogandhi/work/go/src/github.com/fatih/motion
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
resolved root: /Users/rogandhi/work/go/src/github.com/fatih/motion
> git ls-files -- astcontext/parser.go
resolved root: /Users/rogandhi/work/go/src/github.com/fatih/motion
> git symbolic-ref --short HEAD
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :astcontext/parser.go
resolved root: /Users/rogandhi/work/go/src/github.com/fatih/motion
resolved root: /Users/rogandhi/work/go/src/github.com/fatih/motion
> git symbolic-ref --short HEAD
> git ls-files -- astcontext/parser.go
> git diff --name-status
> git diff --staged --name-status
> git ls-files --others --exclude-standard
> git --no-pager show :astcontext/parser.go


## Output channel: snippets


## Output channel: go
[Error  - 12:23:21 PM] Starting client failed: 
  Message: json: cannot unmarshal object into Go struct field PublishDiagnosticsClientCapabilities.capabilities.textDocument.publishDiagnostics.tagSupport of type bool
  Code: -32700 

```

## Describe the bug

When a `go` file is opened, `gopls` fails to start with the error mentioned above.

The issue is reproducible with `min.vim`.

## `coc-settings.json`

```json
{
    "java.jdt.ls.vmargs": "-noverify -Xmx2G -XX:+UseG1GC -XX:+UseStringDeduplication",
    "java.errors.incompleteClasspath.severity": "ignore",
    "java.completion.guessMethodArguments": true,
    "tslint.jsEnable": true,
    "suggest.maxCompleteItemCount": 10,
    "suggest.minTriggerInputLength": 2,
    "explorer.icon.enableNerdfont": true,
    "go.goplsOptions": {
        "deepCompletion": true,
        "completeUnimported": true
    },
    "diagnostic.checkCurrentLine": true,
    "diagnostic.locationlist": false,
    "snippets.autoTrigger": true,
    "suggest.noselect": false,
    "snippets.shortcut": "~"
}
```

**Comment by ronakg** [comment] 2020-03-06 03:38
Tested with Go version 1.12.17 and 1.14. Same issue for both.

**Comment by fannheyward** [comment] 2020-03-06 03:41
Are you using `coc-go`? Can you try if https://github.com/neoclide/coc.nvim/wiki/Language-servers#go works?

```
"languageserver": {
    "golang": {
      "command": "go-langserver",
      "filetypes": ["go"],
      "initializationOptions": {
        "gocodeCompletionEnabled": true,
        "diagnosticsEnabled": true,
        "lintTool": "golint"
      }
    }
  }
```

**Comment by chemzqm** [comment] 2020-03-06 04:46
It's bug of gopls which expect `tagSupport` field to be boolean, until the server get fix for this, we could remove `tagSupport` from initialize notification.

**Closed** 2020-03-06 04:48 UTC

**Comment by fannheyward** [comment] 2020-03-06 04:59
According https://github.com/golang/tools/blob/de023d59a5d12fe28f29c985eb1f744aae7e7d73/internal/lsp/protocol/tsprotocol.go#L539 and https://github.com/golang/tools/blob/de023d59a5d12fe28f29c985eb1f744aae7e7d73/internal/lsp/protocol/tsprotocol.go#L698, gopls's tagSupport field is float64, not boolean.

I can't reproduce this issue by `languageserver`.

**Comment by fannheyward** [comment] 2020-03-06 04:59
@ronakg what's your `gopls version`?

**Comment by fannheyward** [comment] 2020-03-06 05:28
Same issue https://github.com/neoclide/coc.nvim/issues/1625. I think this issue is caused by outdated gopls.

**Comment by ronakg** [comment] 2020-03-06 18:30
Updating `gopls` using `CocCommand go.install.pls` seems to have fixed the issue. Thanks.

**Comment by aaronireland** [comment] 2020-11-03 23:17
> mma

Can you explain how you did this? I'm not sure what the syntax is. Is this something I should add as an autocmd in my vimrc?
