### ISSUE TITLE
Not intended character insertion after navigating on active extensions

### ISSUE THREAD

**Issue by fabricio7p** [neoclide/coc.nvim#2263] opened 2020-08-19 15:53 UTC
## How to reproduce
- Open list extensions with `CocList extensions` (defualt to `<space> + e`)
 
- Hold arrow down or up key

## Result from CocInfo
```
## versions

vim version: VIM - Vi IMproved 8.2 8020814
node version: v14.4.0
coc.nvim version: 0.0.78-d7b3084375
term: dumb
platform: linux

## Output channel: prettier


[Trace - 19/08/2020 11:48:13:] Formatted file: file:///home/fabricio7p/Documents/Projects/Development/Freelas/Plin/plin-condominios-web/src/app/views/Pages/Ajuda/PC-122tmp/ImportBtn.jsx


[Trace - 19/08/2020 11:48:13:] Prettier format edits: [
  {
    "range": {
      "start": {
        "character": 0,
        "line": 0
      },
      "end": {
        "character": 0,
        "line": 33
      }
    },
    "newText": "import React from 'react';\n// import { fileUploadUtils } from 'app/utils'\n\n// placeholder\n\nimport './style.css';\n\nconst fileUploadUtils = {\n  fileTypes: 'test',\n  handleCanUpload: e => console.log(e),\n  handleSubmit: e => console.log(e),\n};\n\nconst ImportBtn = () => {\n  const handleSubmit = ev => {};\n\n  return (\n    <button className=\"import-btn\">\n      <input\n        onChange={e => handleSubmit(e)}\n        type=\"file\"\n        className=\"import-btn__input\"\n      />\n      <div className=\"import-btn__textwrap\">\n        <i className=\"material-icons\">backup</i>\n        Importar Planilha\n      </div>\n    </button>\n  );\n};\n\nexport default ImportBtn;\n"
  }
]


[Trace - 19/08/2020 11:48:23:] Formatted file: file:///home/fabricio7p/Documents/Projects/Development/Freelas/Plin/plin-condominios-web/src/app/views/Pages/Ajuda/PC-122tmp/ImportBtn.jsx


[Trace - 19/08/2020 11:48:23:] Prettier format edits: [
  {
    "range": {
      "start": {
        "character": 0,
        "line": 0
      },
      "end": {
        "character": 0,
        "line": 30
      }
    },
    "newText": "import React from 'react';\n// import { fileUploadUtils } from 'app/utils'\nimport './style.css';\n\n// placeholder\nconst fileUploadUtils = {\n  fileTypes: 'test',\n  handleCanUpload: e => console.log(e),\n  handleSubmit: e => console.log(e),\n};\n\nconst ImportBtn = () => {\n  const handleSubmit = ev => {};\n\n  return (\n    <button className=\"import-btn\">\n      <input\n        onChange={e => handleSubmit(e)}\n        type=\"file\"\n        className=\"import-btn__input\"\n      />\n      <div className=\"import-btn__textwrap\">\n        <i className=\"material-icons\">backup</i>\n        Importar Planilha\n      </div>\n    </button>\n  );\n};\n\nexport default ImportBtn;\n"
  }
]


[Trace - 19/08/2020 11:55:00:] Formatted file: file:///home/fabricio7p/Documents/Projects/Development/Freelas/Plin/plin-condominios-web/src/app/views/Pages/Ajuda/PC-122tmp/ImportBtn.jsx


[Trace - 19/08/2020 11:55:00:] Prettier format edits: [
  {
    "range": {
      "start": {
        "character": 0,
        "line": 0
      },
      "end": {
        "character": 0,
        "line": 32
      }
    },
    "newText": "import React from 'react';\n// import { fileUploadUtils } from 'app/utils'\nimport './style.css';\n\n// placeholder\nconst fileUploadUtils = {\n  fileTypes: 'test',\n  handleCanUpload: e => console.log(e),\n  handleSubmit: e => console.log(e),\n};\n\nconst ImportBtn = () => {\n  const handleSubmit = e => {\n    console.log(e);\n  };\n\n  return (\n    <button className=\"import-btn\">\n      <input\n        onChange={e => handleSubmit(e)}\n        type=\"file\"\n        className=\"import-btn__input\"\n      />\n      <div className=\"import-btn__textwrap\">\n        <i className=\"material-icons\">backup</i>\n        Importar Planilha\n      </div>\n    </button>\n  );\n};\n\nexport default ImportBtn;\n"
  }
]


[Trace - 19/08/2020 11:55:40:] Formatted file: file:///home/fabricio7p/Documents/Projects/Development/Freelas/Plin/plin-condominios-web/src/app/views/Pages/Ajuda/PC-122tmp/ImportBtn.jsx


[Trace - 19/08/2020 11:55:40:] Prettier format edits: [
  {
    "range": {
      "start": {
        "character": 0,
        "line": 0
      },
      "end": {
        "character": 0,
        "line": 32
      }
    },
    "newText": "import React from 'react';\n// import { fileUploadUtils } from 'app/utils'\nimport './style.css';\n\n// placeholder\nconst fileUploadUtils = {\n  fileTypes: 'test',\n  handleCanUpload: e => console.log(e),\n  handleSubmit: e => console.log(e),\n};\n\nconst ImportBtn = () => {\n  const handleSubmit = e => {\n    console.log(e.target.files[0]);\n  };\n\n  return (\n    <button className=\"import-btn\">\n      <input\n        onChange={e => handleSubmit(e)}\n        type=\"file\"\n        className=\"import-btn__input\"\n      />\n      <div className=\"import-btn__textwrap\">\n        <i className=\"material-icons\">backup</i>\n        Importar Planilha\n      </div>\n    </button>\n  );\n};\n\nexport default ImportBtn;\n"
  }
]


[Trace - 19/08/2020 11:57:41:] Formatted file: file:///home/fabricio7p/Documents/Projects/Development/Freelas/Plin/plin-condominios-web/src/app/views/Pages/Ajuda/PC-122tmp/ImportBtn.jsx


[Trace - 19/08/2020 11:57:41:] Prettier format edits: [
  {
    "range": {
      "start": {
        "character": 0,
        "line": 0
      },
      "end": {
        "character": 0,
        "line": 36
      }
    },
    "newText": "import React from 'react';\n// import { fileUploadUtils } from 'app/utils'\nimport './style.css';\n\n// placeholder\nconst fileUploadUtils = {\n  fileTypes: 'test',\n  handleCanUpload: e => true,\n  handleSubmit: e => console.log(e),\n};\n\nconst ImportBtn = () => {\n  const handleSubmit = e => {\n    console.log(e.target.files[0]);\n\n    if (!!handleCanUpload(e)) {\n    }\n  };\n\n  return (\n    <button className=\"import-btn\">\n      <input\n        onChange={e => handleSubmit(e)}\n        type=\"file\"\n        className=\"import-btn__input\"\n      />\n      <div className=\"import-btn__textwrap\">\n        <i className=\"material-icons\">backup</i>\n        Importar Planilha\n      </div>\n    </button>\n  );\n};\n\nexport default ImportBtn;\n"
  }
]


[Trace - 19/08/2020 11:58:01:] Formatted file: file:///home/fabricio7p/Documents/Projects/Development/Freelas/Plin/plin-condominios-web/src/app/views/Pages/Ajuda/PC-122tmp/ImportBtn.jsx


[Trace - 19/08/2020 11:58:01:] Prettier format edits: [
  {
    "range": {
      "start": {
        "character": 0,
        "line": 0
      },
      "end": {
        "character": 0,
        "line": 36
      }
    },
    "newText": "import React from 'react';\n// import { fileUploadUtils } from 'app/utils'\nimport './style.css';\n\n// placeholder\nconst fileUploadUtils = {\n  fileTypes: 'test',\n  handleCanUpload: e => true,\n  handleSubmit: e => console.log(e),\n};\n\nconst ImportBtn = () => {\n  const { handleCanUpload } = fileUploadUtils;\n  const handleSubmit = e => {\n    console.log(e.target.files[0]);\n\n    if (!!handleCanUpload(e)) {\n    }\n  };\n\n  return (\n    <button className=\"import-btn\">\n      <input\n        onChange={e => handleSubmit(e)}\n        type=\"file\"\n        className=\"import-btn__input\"\n      />\n      <div className=\"import-btn__textwrap\">\n        <i className=\"material-icons\">backup</i>\n        Importar Planilha\n      </div>\n    </button>\n  );\n};\n\nexport default ImportBtn;\n"
  }
]


[Trace - 19/08/2020 12:03:18:] Formatted file: file:///home/fabricio7p/Documents/Projects/Development/Freelas/Plin/plin-condominios-web/src/app/views/Pages/Ajuda/PC-122tmp/ImportBtn.jsx


[Trace - 19/08/2020 12:03:18:] Prettier format edits: [
  {
    "range": {
      "start": {
        "character": 0,
        "line": 0
      },
      "end": {
        "character": 0,
        "line": 38
      }
    },
    "newText": "import React from 'react';\n// import { fileUploadUtils } from 'app/utils'\nimport './style.css';\n\n// placeholder\nconst fileUploadUtils = {\n  fileTypes: 'test',\n  handleCanUpload: e => true,\n  handleSubmit: e => console.log(e),\n};\n\nconst ImportBtn = () => {\n  const { handleCanUpload } = fileUploadUtils;\n  const formData = new FormData();\n  const handleSubmit = e => {\n    console.log(e.target.files[0]);\n\n    if (!!handleCanUpload(e)) {\n    }\n  };\n\n  return (\n    <button className=\"import-btn\">\n      <input\n        onChange={e => handleSubmit(e)}\n        type=\"file\"\n        className=\"import-btn__input\"\n      />\n      <div className=\"import-btn__textwrap\">\n        <i className=\"material-icons\">backup</i>\n        Importar Planilha\n      </div>\n    </button>\n  );\n};\n\nexport default ImportBtn;\n"
  }
]


[Trace - 19/08/2020 12:04:37:] Formatted file: file:///home/fabricio7p/Documents/Projects/Development/Freelas/Plin/plin-condominios-web/src/app/views/Pages/Ajuda/PC-122tmp/ImportBtn.jsx


[Trace - 19/08/2020 12:04:37:] Prettier format edits: [
  {
    "range": {
      "start": {
        "character": 0,
        "line": 0
      },
      "end": {
        "character": 0,
        "line": 38
      }
    },
    "newText": "import React from 'react';\n// import { fileUploadUtils } from 'app/utils'\nimport './style.css';\n\n// placeholder\nconst fileUploadUtils = {\n  fileTypes: 'test',\n  handleCanUpload: e => true,\n  handleSubmit: e => console.log(e),\n};\n\nconst ImportBtn = () => {\n  const { handleCanUpload } = fileUploadUtils;\n  const formData = new FormData();\n  const handleSubmit = e => {\n    console.log(e.target.files[0]);\n\n    if (!!handleCanUpload(file)) {\n      formData.append('table', file, file.name);\n    }\n  };\n\n  return (\n    <button className=\"import-btn\">\n      <input\n        onChange={e => handleSubmit(e)}\n        type=\"file\"\n        className=\"import-btn__input\"\n      />\n      <div className=\"import-btn__textwrap\">\n        <i className=\"material-icons\">backup</i>\n        Importar Planilha\n      </div>\n    </button>\n  );\n};\n\nexport default ImportBtn;\n"
  }
]


[Trace - 19/08/2020 12:05:03:] Formatted file: file:///home/fabricio7p/Documents/Projects/Development/Freelas/Plin/plin-condominios-web/src/app/views/Pages/Ajuda/PC-122tmp/ImportBtn.jsx


[Trace - 19/08/2020 12:05:03:] Prettier format edits: [
  {
    "range": {
      "start": {
        "character": 0,
        "line": 0
      },
      "end": {
        "character": 0,
        "line": 38
      }
    },
    "newText": "import React from 'react';\n// import { fileUploadUtils } from 'app/utils'\nimport './style.css';\n\n// placeholder\nconst fileUploadUtils = {\n  fileTypes: 'test',\n  handleCanUpload: e => true,\n  handleSubmit: e => console.log(e),\n};\n\nconst ImportBtn = () => {\n  const { handleCanUpload } = fileUploadUtils;\n  const formData = new FormData();\n  const handleSubmit = e => {\n    const file = e.target.files[0];\n    if (!!handleCanUpload(file)) {\n      formData.append('table', file, file.name);\n      console.log(formData);\n    }\n  };\n\n  return (\n    <button className=\"import-btn\">\n      <input\n        onChange={e => handleSubmit(e)}\n        type=\"file\"\n        className=\"import-btn__input\"\n      />\n      <div className=\"import-btn__textwrap\">\n        <i className=\"material-icons\">backup</i>\n        Importar Planilha\n      </div>\n    </button>\n  );\n};\n\nexport default ImportBtn;\n"
  }
]


## Output channel: snippets

[Info 11:47:54] Using ultisnips directories: UltiSnips /home/fabricio7p/.config/coc/ultisnips
[Info 11:47:54] Using ultisnips python command: pyx

## Output channel: tsserver

[Info  - 11:47:54] Forking TSServer
PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/fabricio7p/.local/bin:/home/fabricio7p/.local/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/fabricio7p/.local/bin 
[Info  - 11:47:54] Started TSServer
{
  "path": "/home/fabricio7p/Documents/Projects/Development/Freelas/Plin/plin-condominios-web/node_modules/typescript/lib",
  "_api": {
    "versionString": "3.9.7",
    "version": "3.9.7"
  }
}
```

## Description
- Extension list will force close
- Random character will be inserted

### Before
![image](https://user-images.githubusercontent.com/46208058/90659231-d17eda00-e21a-11ea-9d02-69593422f744.png)

### After
![image](https://user-images.githubusercontent.com/46208058/90659292-dfccf600-e21a-11ea-9b1b-62ac617cbbbc.png)

**Comment by oblitum** [comment] 2020-08-19 18:40
Duplicate of #1020

**Closed by oblitum** 2020-08-19 18:40 UTC

**Comment by oblitum** [comment] 2020-08-19 18:42
Related #1378

**Comment by chemzqm** [comment] 2020-08-21 06:29
Avoid hold arrow down or up key
