### ISSUE TITLE
Incorrect scroll bar position when there's window on the left after upgrading to 153fdc4

### ISSUE THREAD

**Issue by Frederick888** [neoclide/coc.nvim#3157] opened 2021-06-23 07:03 UTC
## Result from CocInfo

```
undefined## versions

vim version: NVIM v0.4.4
node version: v16.3.0
coc.nvim version: 0.0.80-91c1114046
coc.nvim directory: /Users/fzhang/.vim/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2021-06-23T17:00:10.592 INFO (pid:55452) [services] - registered service "languageserver.ccls"
2021-06-23T17:00:10.595 INFO (pid:55452) [services] - registered service "languageserver.dockerfile"
2021-06-23T17:00:10.595 INFO (pid:55452) [services] - registered service "languageserver.bash"
2021-06-23T17:00:10.595 INFO (pid:55452) [services] - registered service "languageserver.cmake"
2021-06-23T17:00:10.595 INFO (pid:55452) [services] - registered service "languageserver.sql"
2021-06-23T17:00:10.620 INFO (pid:55452) [services] - registered service "diagnostic-languageserver"
2021-06-23T17:00:10.739 INFO (pid:55452) [coc-git] - Looking for git in: git
2021-06-23T17:00:10.910 WARN (pid:55452) [attach] - Plugin not ready when received "runCommand" [ 'coc-helper.internal.didVimEvent_2', 'CocGitStatusChange' ]
2021-06-23T17:00:10.970 INFO (pid:55452) [coc-groovy] - Starting Groovy Language Server with: /usr/local/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home/bin/java -Dfile.encoding=utf-8 -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar /Users/fzhang/.config/coc/extensions/node_modules/coc-groovy/server/groovy-language-server-all.jar
2021-06-23T17:00:11.065 INFO (pid:55452) [language-client-index] - Language server "groovy" started with 55584
2021-06-23T17:00:11.206 INFO (pid:55452) [coc-java] - Using java from /usr/local/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home, version: 11
2021-06-23T17:00:11.406 INFO (pid:55452) [coc-java] - JDT Language Server starting at /Users/fzhang/Programming/Java/demo
2021-06-23T17:00:11.407 INFO (pid:55452) [services] - registered service "java"
2021-06-23T17:00:11.435 INFO (pid:55452) [language-client-index] - Language server "java" started with 55639
2021-06-23T17:00:11.958 WARN (pid:55452) [attach] - Plugin not ready when received "runCommand" [ 'coc-helper.internal.didVimEvent_2', 'CocGitStatusChange' ]
2021-06-23T17:00:11.968 INFO (pid:55452) [plugin] - coc.nvim 0.0.80-91c1114046 initialized with node: v16.3.0 after 1497ms
2021-06-23T17:00:14.638 INFO (pid:55452) [attach] - receive notification: showInfo []
2021-06-23T17:00:14.649 INFO (pid:55452) [attach] - receive request: CocAutocmd [ 'BufReadCmd', 'output', 'output:///info' ]
2021-06-23T17:00:14.659 INFO (pid:55452) [attach] - receive notification: doAutocmd [ 1 ]
2021-06-23T17:00:14.675 INFO (pid:55452) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'CocGitStatusChange' ]
2021-06-23T17:00:20.191 INFO (pid:55452) [attach] - receive notification: doAutocmd [ 1 ]
2021-06-23T17:00:20.252 INFO (pid:55452) [attach] - receive notification: runCommand [ 'coc-helper.internal.didVimEvent_2', 'CocGitStatusChange' ]
2021-06-23T17:00:23.626 INFO (pid:55452) [attach] - receive notification: showInfo []
```

## Describe the bug

Incorrect scroll bar position for floating windows when there's window on the left after upgrading to 153fdc4.

## Reproduce the bug

**We will close your issue when you don't provide minimal vimrc and we can't
reproduce it**

- Create file `mini.vim` with：

```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

" vim-plug
call plug#begin()

Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

"" ==== Start Coc Configurations ====

" Some servers have issues with backup files, see #649
set nobackup
set nowritebackup

" Better display for messages
set cmdheight=2

" You will have bad experience for diagnostic messages when it's default 4000.
set updatetime=300

" Don't give |ins-completion-menu| messages.
set shortmess+=c

" Always show the signcolumn, otherwise it would shift the text each time
" diagnostics appear/become resolved.
if has("patch-8.1.1564")
 " Recently vim can merge signcolumn and number column into one
 set signcolumn=number
else
 set signcolumn=yes
endif

" Single column signs
let g:coc_status_error_sign = "\U2717 "
let g:coc_status_warning_sign = "\U26A0 "

" Use K to show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>
function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h ' . expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction

" ==== End Coc Configurations ====

" vim: set tabstop=4 softtabstop=0 expandtab shiftwidth=2 smarttab:
```

- Start (neo)vim with command: `vim -u mini.vim`
- Open a file
- Ctrl-w v, Ctrl-w l
- Move cursor to some symbol, <kbd>K</kbd> to show docs

## Screenshots (optional)

Previously using 0692698 (correct): 
<img width="1693" alt="image" src="https://user-images.githubusercontent.com/4507647/123050399-01eb6200-d444-11eb-951f-4ee4a4e9be74.png">

Now using 153fdc4 (incorrect):
<img width="1620" alt="image" src="https://user-images.githubusercontent.com/4507647/123050501-20e9f400-d444-11eb-9c20-5ffc3a9e7bc5.png">

**Comment by fannheyward** [comment] 2021-06-24 06:21
Tested with nvim 0.4.4 on macOS with Python files, can't reproduce.

**Comment by Frederick888** [comment] 2021-06-24 07:35
I can reproduce using nvim 0.4.4 on Linux with Python as well:

![image](https://user-images.githubusercontent.com/4507647/123221546-696fe300-d512-11eb-8f1e-669d85ddc75f.png)

I'll try this out again tomorrow on macOS.

**Comment by fannheyward** [comment] 2021-06-24 07:39
<img width="1189" alt="截屏2021-06-24 下午3 39 14" src="https://user-images.githubusercontent.com/345274/123222256-56edad80-d502-11eb-85a5-d0257cd7d799.png">

**Comment by Frederick888** [comment] 2021-06-24 07:45
@fannheyward Could you share your test file? Mine is
```python
#!/usr/bin/env python3

def main():
    """
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis auctor metus ac consectetur feugiat. Etiam id nisl rutrum metus sollicitudin dictum. Aliquam ut ligula lacus. Ut odio sapien, condimentum id ornare at, venenatis sit amet risus. Nullam lectus elit, tristique vel fermentum quis, dapibus vel nulla. In neque nunc, blandit eu faucibus sed, finibus id augue. Morbi ac felis quis tellus dignissim congue vitae ut massa. Praesent pretium ac turpis sit amet auctor. Sed magna leo, scelerisque id elit sed, aliquet imperdiet tortor. Praesent ultricies erat et vestibulum rhoncus. In bibendum sed lacus id tincidunt. Nam a blandit lorem. Aenean suscipit leo ut convallis ultrices. Quisque condimentum augue hendrerit, fringilla tortor sed, feugiat tellus. Etiam enim turpis, placerat in tellus nec, vestibulum laoreet sapien.

    Aliquam finibus ut nunc fermentum maximus. Donec sed nisl placerat, blandit odio vel, ultrices leo. Vestibulum malesuada in elit non volutpat. Nunc ultricies nulla ut nunc porttitor, nec tristique lectus blandit. Etiam ac est vitae ex ultricies efficitur eget id metus. Donec vulputate, est id tristique cursus, purus tortor vehicula tortor, eget iaculis metus nulla sit amet est. Sed eget consectetur mauris. Donec egestas, diam et volutpat ultrices, nisl turpis vehicula ligula, eget ullamcorper nunc purus et nibh. Integer pharetra molestie dolor, vel fringilla quam tempus non. Aenean lacinia viverra tristique. Aliquam venenatis, elit sit amet efficitur posuere, nisi massa porta ex, non pellentesque eros libero blandit libero. Phasellus eu porttitor justo, sed sagittis augue. Etiam vel tortor ac nibh luctus egestas sit amet ac lorem. Nunc luctus blandit odio, quis rhoncus libero. Sed quis neque condimentum, tristique tellus vel, rhoncus purus. Phasellus eget augue dui.

    Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec et vulputate metus. Etiam vel elementum augue, a tristique elit. Vestibulum quis lacus ut neque maximus auctor. Phasellus non hendrerit odio. Nulla porta nulla dolor, vel maximus libero pretium non. Integer ullamcorper dolor massa, non scelerisque felis fermentum nec. Suspendisse commodo libero quis lorem luctus, quis viverra ex suscipit.

    Maecenas dictum lorem at lectus vehicula posuere. Sed sit amet felis tortor. Proin vel gravida nibh. Maecenas rhoncus ultrices mauris id placerat. Phasellus ac felis quis dui varius iaculis. Sed sed arcu tempus, dignissim tortor vitae, interdum leo. Etiam blandit tristique nisi at lobortis. Donec pulvinar leo id turpis gravida, eu sagittis eros eleifend. Aliquam purus felis, ullamcorper sed dignissim quis, molestie nec purus. In luctus, lectus pretium imperdiet iaculis, turpis orci congue sem, vitae pharetra mi quam nec nisl.

    Praesent purus ex, fringilla sed tincidunt nec, finibus hendrerit lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sagittis eleifend nulla, quis rhoncus felis pharetra id. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi placerat neque ut nisl pretium venenatis at non elit. Donec convallis dolor tristique, ultricies arcu ac, malesuada purus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam ex nisi, dignissim nec ullamcorper ac, volutpat in dolor.
    """
    pass

if __name__ == "__main__":
    main()
```

Btw just tested disabling all coc extensions except for coc-pyright, was still able to reproduce.

**Comment by fannheyward** [comment] 2021-06-24 08:08
Tested with same mini.vim, still can't reproduce on nvim 0.4 & 0.5

**Comment by chemzqm** [comment] 2021-06-25 07:24
Fixed on latest release branch of coc.nvim.

**Closed by chemzqm** 2021-06-25 07:24 UTC
Labels: bug
