### ISSUE TITLE
langserver-go keeps unexpectedly opening window with debug output

### ISSUE THREAD

**Issue by Dbz** [neoclide/coc.nvim#179] opened 2018-11-25 00:30 UTC
**Describe the bug**
When I open a new file, langserver-go will open up a window in my vim terminal with output after attempting to run my file. I do not want this automatically happening.

**To Reproduce**
1. Create file `touch main.go`
2. open file `vim main.go`
You will see output below the status line: `[coc.nvim] service languageserver.golang started`
3. Start typing `package main` and a window will be created with debug output

![image](https://user-images.githubusercontent.com/628429/48974184-a8a9c080-f005-11e8-909c-11fa95dd631d.png)

**Expected behavior**
Nothing will happen as I am typing in a new file

**Desktop (please complete the following information):**
 - Terminal: iTerm2
 - Version: v3.2.5

**Additional context**
This also happens randomly when working on files, but it is very consistent when opening a new file. I don't know if it has to do my my directory structure. Here is my directory and path variables:

directory: `/Users/dbz/development/go/src/github.com/udemy_channels`
$GOPATH: `/Users/dbz/development/go`
($GOPATH is appended onto the very end of $PATH)
$PATH: `/Users/dbz/apache-cassandra-3.11.2/bin:./bin:/Users/dbz/bin:/Users/dbz/.rbenv/bin:/Users/dbz/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/9.4/bin:/usr/local/mysql/bin:/Users/dbz/bin:/Users/dbz/development/go/bin`

**Comment by oblitum** [comment] 2018-11-25 00:35
I also got that window while in a working source, but after typing `(` for a function. Choosing the function from the popup menu avoided the issue, but just keep typing it without using the menu and reaching `(` caused the bug for me.

**Comment by chemzqm** [comment] 2018-11-25 01:17
The output window will be opened when language server log errors by default.
Add  `"revealOutputChannelOn": "never",` to configuration section of your server to disable this behavior.

**Comment by chemzqm** [comment] 2018-11-25 01:20
There should be Message contains `Error` which should be fixed with your language server.

**Comment by chemzqm** [comment] 2018-11-25 12:48
Try remove autocmd of `showSignatureHelp` like:
```
  autocmd CursorHoldI * silent call CocActionAsync('showSignatureHelp')
```
The error might caused by the server is not ready to parse signature.
You can still have triggered signature without this autocmd.

**Comment by Dbz** [comment] 2018-11-25 20:41
Is there a way to disable this only for Go and not for other languages like Ruby?

**Comment by oblitum** [comment] 2018-11-25 20:43
It's on wiki: https://github.com/neoclide/coc.nvim/wiki/Language-servers#go.

**Comment by chemzqm** [comment] 2018-11-25 21:50
`3` in `[3 - 4:25` should be `error`, it's fixed on master.

**Closed by chemzqm** 2018-11-25 21:50 UTC
Labels: question

**Comment by Dbz** [comment] 2018-11-26 02:29
@oblitum just a note on the documentation. JSON doesn't support comments (ridiculous, I know), so if people copy/paste the json configs with comments (`//`), they will break and they may not know why.

**Comment by oblitum** [comment] 2018-11-26 02:31
@Dbz `coc-settings.json` uses cJSON format, which do accept comments.

**Comment by oblitum** [comment] 2018-11-26 02:32
It's mentioned here: https://github.com/neoclide/coc.nvim/wiki/Using-configuration-file.

**Comment by Dbz** [comment] 2018-11-26 02:34
My mistake!

Seriously though, thank you @oblitum and @chemzqm for working on this plugin. It is great.

**Comment by oblitum** [comment] 2018-11-26 02:36
@Dbz np, all kudos to @chemzqm, currently I'm just trying to help and playing with it.

**Comment by oblitum** [comment] 2018-11-26 02:37
@Dbz recommendation for Go, you may use it in parallel to vim-go, because the Go LSP server still doesn't offer many features.

**Comment by Dbz** [comment] 2018-11-26 02:42
Yeah, I am using `vim-go` as well! It might be worth mentioning that in the wiki near the Go server config.
