### ISSUE TITLE
Items containing `@` do not appear in the completion items

### ISSUE THREAD

**Issue by yaegassy** [neoclide/coc.nvim#4348] opened 2022-11-08 05:40 UTC
## Result from CocInfo

```
## versions

vim version: NVIM v0.9.0-dev-279+gd187c00fa
node version: v18.12.0
coc.nvim version: 0.0.82-a82e5ad 2022-11-07 18:34:43 +0800
coc.nvim directory: /Users/yaegassy/.local/share/nvim/plugged/coc.nvim
term: iTerm.app
platform: darwin
```

## Describe the bug

It appears that items with `@` in the completion item are not displayed. I used `volar` language server and checked with vue files.

- Related issue
  - <https://github.com/yaegassy/coc-volar/issues/226>

The trace logs show that the language server's `textDocument/completion` response also includes an entry containing `@`.

**Trace Log**:

```
[Trace - 2:30:53 PM] Received response 'textDocument/completion - (24)' in 34ms.
Result: {
    "isIncomplete": false,
    "items": [
// ...snip
        {
            "label": "@click",
            "kind": 23,
            "textEdit": {
                "range": {
                    "start": {
                        "line": 2,
                        "character": 12
                    },
                    "end": {
                        "line": 2,
                        "character": 13
                    }
                },
                "newText": "@click=\"$1\""
            },
            "insertTextFormat": 2,
            "data": {
                "uri": "file:///Users/yaegassy/coc-issue-check/Check.vue",
                "originalItem": {
                    "label": "@click",
                    "kind": 23,
                    "textEdit": {
                        "range": {
                            "start": {
                                "line": 2,
                                "character": 12
                            },
                            "end": {
                                "line": 2,
                                "character": 13
                            }
                        },
                        "newText": "@click=\"$1\""
                    },
                    "insertTextFormat": 2
                },
                "pluginId": 2,
                "sourceMap": {
                    "embeddedDocumentUri": "file:///Users/yaegassy/coc-issue-check/Check.vue.template.html"
                }
            }
        }
// ...snip
    ]
}
```

## Reproduce the bug

**Install coc-volar**:

```
:CocInstall @yaegassy/coc-volar`
```

**Prepare**

```
cd $HOME
npm init vue coc-issue-check
cd coc-issue-check
npm i
```

**Edit**:

See DEMO.

## DEMO (Latest)

https://user-images.githubusercontent.com/188642/200483960-66f44d45-a2b8-441c-b595-ce3c74086a07.mp4

## Screen Shot (Old version of coc.nvim)

In older versions of coc.nvim, completion items with `@` are also displayed correctly.

<img width="333" alt="old-coc-nvim" src="https://user-images.githubusercontent.com/188642/200484008-3a66d1a5-b153-4f22-82bf-6e6a2aae7d7f.png">

**Comment by chemzqm** [comment] 2022-11-08 10:45
The reason is vue-semantic-server returns complete items that requires different start column (with @ replaced), remove `@` from trigger characters of source vue-semantic-server should helps.

**Comment by chemzqm** [comment] 2022-11-08 11:13
Or make vetur source returns the same range as vue-semantic-server.
Unlike VSCode, we have to use single start column for all completion sources, so this need to be fixed by extension.

**Closed by chemzqm** 2022-11-08 11:13 UTC

**Comment by yaegassy** [comment] 2022-11-08 12:54
I added the following code to coc-volar's middleware with reference to coc-vetur.

The completion item appears when you type `@`, but if you type a string after `@`, the completion menu is interrupted.

Can you give me some advice on the code?

```typescript
async function handleProvideCompletionItem(
  document: LinesTextDocument,
  position: Position,
  context: CompletionContext,
  token: CancellationToken,
  next: ProvideCompletionItemsSignature
) {
  const res = await Promise.resolve(next(document, position, context, token));
  const doc = workspace.getDocument(document.uri);
  if (!doc || !res) return [];

  let items: CompletionItem[] = res.hasOwnProperty('isIncomplete')
    ? (res as CompletionList).items
    : (res as CompletionItem[]);

  const pre = doc.getline(position.line).slice(0, position.character);

  if (context.triggerCharacter == '@' || /@\w*$/.test(pre)) {
    items = items.filter((o) => o.label.startsWith('@'));
  }

  return items;
}
```

---


https://user-images.githubusercontent.com/188642/200569690-b1963400-c8ee-452a-9359-42885c057b7a.mp4

**Comment by yaegassy** [comment] 2022-11-08 13:44
I tried with `// @ts-ignore` on `coc-tsserver` and the completion menu disappeared on the next character after the `@` input.

I tried with an older version of coc.nvim (v0.0.81) and the completion menu did not break up when typing the next character after the `@`.

**Comment by chemzqm** [comment] 2022-11-08 13:50
There seems bug with filter input, I'm looking into it.

**Comment by chemzqm** [comment] 2022-11-08 14:49
There used by fix for filterText https://github.com/neoclide/coc.nvim/issues/3918 but the filterText could be corrected and result in first character not match, but the fuzzy score from VSCode requires strong match for first character.

**Comment by chemzqm** [comment] 2022-11-08 15:15
I've made a fix, no need fix by coc-volar any more.

**Comment by yaegassy** [comment] 2022-11-08 21:49
Thanks! 🙇

**Comment by yaegassy** [comment] 2022-11-10 22:01
@chemzqm With this commit, this problem is happening again.<https://github.com/neoclide/coc.nvim/commit/7c6db7546dfa29f1167c53111a00abac4e86e383>

**Comment by chemzqm** [comment] 2022-11-11 06:46
All complete items are shown as expected now, you can filter, the input changed to empty for this case like VSCode, you have to fix the issue by change extension or language server code, to not trigger that unnecessary completion if you think they should not shown with `@`

**Comment by chemzqm** [comment] 2022-11-11 07:26
Made a litter change, so the items not replace trigger character have higher priority.

**Comment by yaegassy** [comment] 2022-11-11 07:42
Currently, completion with @ works fine with LSP clients other than VSCode (e.g. `nvim-lsp` + `nvim-cmp`), so we think it may be difficult to adjust on the language server side, as it may cause problems on another client.

I will try to think in the direction of adjusting the middleware on the extension side, but this comment problem arises.

- <https://github.com/neoclide/coc.nvim/issues/4348#issuecomment-1307169885>

**Comment by yaegassy** [comment] 2022-11-11 08:17
For example, in `coc-tsserver`, the completion candidates are cut off when typing the character after `@`.

- `// @|` 
  - e.g. `@ts-ignore`
- `import {} from '@|'`
  - scoped packafge

**Comment by fannheyward** [comment] 2022-11-11 08:34
> in coc-tsserver, the completion menu disappears when typing the character after @

Reproduced

**Comment by chemzqm** [comment] 2022-11-11 08:37
Should be bug for that case, try the latest release

**Comment by fannheyward** [comment] 2022-11-11 08:44
Tested with coc master, same issue, completion menu disappeared when typing character after @.

**Comment by yaegassy** [comment] 2022-11-11 09:03
I tried this example with the `coc.nvim` source. Here is an example of an import statement for `@bable/core`.

Apparently, only candidates that did not include the `@` prefix were displayed when entering the characters following `@`.


https://user-images.githubusercontent.com/188642/201305101-108eb9cc-6995-4373-b388-51c0e585401b.mp4

**Comment by chemzqm** [comment] 2022-11-11 09:13
I've made a fix.

**Comment by yaegassy** [comment] 2022-11-11 09:17
@chemzqm  Thanks for the adjustment. I was able to check that the problem was resolved in my environment

@fannheyward Thanks for check the operation.
