### ISSUE TITLE
node build/index.js keeps eating CPU.

### ISSUE THREAD

**Issue by kierun** [neoclide/coc.nvim#1498] opened 2020-01-27 14:07 UTC
## versions

vim version: NVIM v0.4.3
node version: v8.17.0
coc.nvim version: 0.0.74-6700e7468d
term: screen-256color
platform: linux

## Messages[coc.nvim]

Installed extension: coc-python

## Describe the bug

After a few minutes of running `nvim`, I get a node.js process eating my CPU till it reaches 100%. It never stops. This is what the command looks like:

```/usr/bin/node --no-warnings /home/usr/.cache/dein/.cache/init.vim/.dein/build/index.js```

## Reproduce the bug

Install CoC via dein, run nvim, look at (h)top.

- Create file `mini.vim` with：

  ```vim
  set nocompatible
  filetype plugin indent on
  syntax on
  set hidden
  set runtimepath^=~/home/usr/.config/nvim/dein.vim/repos/github.com/Shougo/dein.vim
  call dein#begin(expand('~/.cache/dein'))  
  call dein#end()
  call dein#add('neoclide/coc.nvim', {'merge':0, 'rev': 'release'})
  let g:airline#extensions#coc#enabled = 1
  ```

**Comment by fannheyward** [comment] 2020-01-27 14:56
Upgrade your nodejs please, I'm using v13.7, can't reproduce this issue.

**Comment by kierun** [comment] 2020-01-27 15:03
@fannheyward Upgrade to 12.14.1 and I am seeing the issue. Still, it now takes 5/7% of a CPU not 100% so I guess it's better…

**Comment by fannheyward** [comment] 2020-01-27 15:08
Close the issue for now.

**Closed by fannheyward** 2020-01-27 15:08 UTC
